// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: pay/pay.proto

package pay

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/pay"
	"github.com/liujitcn/shop-admin/server/internal/service/pay/biz"
	baseCore "github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// PayService is the server API for PayService service implement.
type PayService struct {
	pay.UnimplementedPayServiceServer
	*baseCore.ShopCore
	payCase *biz.PayCase
}

// NewPayService create a service implement.
// 支付服务
func NewPayService(
	sc *baseCore.ShopCore,
	payCase *biz.PayCase,
) *PayService {
	var ss = PayService{
		ShopCore: sc,
		payCase:  payCase}
	log.Debug("NewPayService.")
	return &ss
}

// PayNotify
// 支付通知
func (s *PayService) PayNotify(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	err := s.payCase.PayNotify(ctx, req)
	if err != nil {
		log.Error("PayNotify err:", err.Error())
		return nil, errors.New("通知失败")
	}

	return &emptypb.Empty{}, nil
}
