// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: pay/pay.proto

package pay

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/pay"
	"github.com/liujitcn/shop-admin/server/internal/service/pay/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// PayService is the server API for PayService service implement.
type PayService struct {
	pay.UnimplementedPayServiceServer
	payCase *biz.PayCase
}

// NewPayService create a service implement.
// 支付服务
func NewPayService(
	ctx *bootstrap.Context,
	payCase *biz.PayCase,
) *PayService {
	var ss = PayService{payCase: payCase}
	log.Debug("NewPayService.")
	return &ss
}

// JsapiPay
// 小程序支付
func (s *PayService) JsapiPay(ctx context.Context, req *pay.PayRequest) (*pay.JsapiPayResponse, error) {
	res, err := s.payCase.JsapiPay(ctx, req)
	if err != nil {
		log.Error("JsapiPay err:", err.Error())
		return nil, errors.New("支付失败")
	}
	return res, nil
}

// H5Pay
// H5支付
func (s *PayService) H5Pay(ctx context.Context, req *pay.PayRequest) (*pay.H5PayResponse, error) {
	res, err := s.payCase.H5Pay(ctx, req)
	if err != nil {
		log.Error("H5Pay err:", err.Error())
		return nil, errors.New("支付失败")
	}
	return res, nil
}

// PayNotify
// 支付通知
func (s *PayService) PayNotify(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	err := s.payCase.PayNotify(ctx, req)
	if err != nil {
		log.Error("PayNotify err:", err.Error())
		return nil, errors.New("通知失败")
	}

	return &emptypb.Empty{}, nil
}
