// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/auth.proto

package admin

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/go-utils/crypto"
	_string "github.com/liujitcn/go-utils/string"
	_time "github.com/liujitcn/go-utils/time"
	"github.com/liujitcn/kratos-kit/auth"
	"github.com/liujitcn/kratos-kit/auth/authn/engine"
	authData "github.com/liujitcn/kratos-kit/auth/data"
	"github.com/liujitcn/kratos-kit/captcha"
	"github.com/liujitcn/kratos-kit/sdk"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/api/gen/go/login"
	_const "github.com/liujitcn/shop-admin/server/internal/const"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// AuthService is the server API for AuthService service implement.
type AuthService struct {
	admin.UnimplementedAuthServiceServer
	*core.ShopCore
	baseUserCase *biz.BaseUserCase
	baseRoleCase *biz.BaseRoleCase
	baseDeptCase *biz.BaseDeptCase
	baseMenuCase *biz.BaseMenuCase
}

// NewAuthService create a service implement.
// Admin用户登录认证服务
func NewAuthService(
	sc *core.ShopCore,
	userCase *biz.BaseUserCase,
	roleCase *biz.BaseRoleCase,
	deptCase *biz.BaseDeptCase,
	menuCase *biz.BaseMenuCase,
) *AuthService {
	var ss = AuthService{
		ShopCore:     sc,
		baseUserCase: userCase,
		baseRoleCase: roleCase,
		baseDeptCase: deptCase,
		baseMenuCase: menuCase,
	}
	log.Debug("NewAuthService.")
	return &ss
}

// Login
// 登录
func (s *AuthService) Login(ctx context.Context, req *login.LoginRequest) (*login.LoginResponse, error) {
	if req.GetCaptchaId() == "" || req.GetCaptchaCode() == "" {
		return nil, errors.New("验证码不存在")
	}
	if !captcha.Verify(req.GetCaptchaId(), req.GetCaptchaCode(), true) {
		return nil, errors.New("验证码错误")
	}

	user, err := s.baseUserCase.GetFromUserName(ctx, req.GetUserName())
	if err != nil {
		return nil, errors.New("用户不存在")
	}
	if user.Status != int32(common.Status_ENABLE) {
		return nil, errors.New("用户状态错误")
	}
	err = crypto.Verify(req.GetPassword(), user.Password)
	if err != nil {
		log.Errorf("verify pwd err: %s", err.Error())
		return nil, errors.New("密码错误")
	}

	// 查询角色信息
	var role *models.BaseRole
	role, err = s.baseRoleCase.GetFromID(ctx, user.RoleID)
	if err != nil {
		return nil, errors.New("角色不存在")
	}

	// 查询部门信息
	var dept *models.BaseDept
	dept, err = s.baseDeptCase.GetFromID(ctx, user.DeptID)
	if err != nil {
		return nil, errors.New("部门不存在")
	}

	// 生成访问令牌
	var accessToken, refreshToken string
	accessToken, refreshToken, err = s.UserToken.GenerateToken(&authData.UserTokenPayload{
		UserId:   user.ID,
		UserName: user.UserName,
		RoleId:   user.RoleID,
		RoleCode: role.Code,
		RoleName: role.Name,
		DeptId:   user.DeptID,
		DeptName: dept.Name,
	})
	if err != nil {
		return nil, errors.New("登录失败")
	}

	// Token 有效期
	expiresIn := s.UserToken.GetAccessTokenExpires()

	return &login.LoginResponse{
		TokenType:    engine.BearerWord,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    expiresIn,
	}, nil
}

// GetUserInfo
// 获取已经登录的用户的数据
func (s *AuthService) GetUserInfo(ctx context.Context, req *emptypb.Empty) (*admin.UserInfo, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}
	var baseUser *models.BaseUser
	baseUser, err = s.baseUserCase.GetFromID(ctx, authInfo.UserId)
	if err != nil {
		return nil, errors.New("用户不存在")
	}
	if baseUser.Status != int32(common.Status_ENABLE) {
		return nil, errors.New("用户状态错误")
	}

	// 查询角色信息
	var baseRole *models.BaseRole
	baseRole, err = s.baseRoleCase.GetFromID(ctx, baseUser.RoleID)
	if err != nil {
		return nil, errors.New("角色不存在")
	}

	condition := &data.BaseMenuCondition{
		Types:  []int32{int32(common.BaseMenuType_BUTTON)},
		Status: int32(common.Status_ENABLE),
	}
	//是否超级管理员
	if baseRole.Code != _const.BaseRoleCode_Super {
		condition.Ids = _string.ConvertJsonStringToInt64Array(baseRole.Menus)
	}

	//用户权限
	baseMenus := make([]*models.BaseMenu, 0)
	baseMenus, err = s.baseMenuCase.List(ctx, condition)
	permission := make([]string, 0)
	if err != nil {
		return nil, common.ErrorAccessForbidden("用户权限不存在")
	}
	for _, item := range baseMenus {
		permission = append(permission, item.Path)
	}
	return &admin.UserInfo{
		UserName:   baseUser.UserName,
		NickName:   baseUser.NickName,
		Phone:      baseUser.Phone,
		Avatar:     baseUser.Avatar,
		Permission: permission,
		RoleCode:   baseRole.Code,
	}, nil
}

// GetUserMenu
// 获取已经登录的用户菜单
func (s *AuthService) GetUserMenu(ctx context.Context, req *emptypb.Empty) (*admin.TreeRouteResponse, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	// 查询角色信息
	var baseRole *models.BaseRole
	baseRole, err = s.baseRoleCase.GetFromID(ctx, authInfo.RoleId)
	if err != nil {
		return nil, errors.New("角色不存在")
	}

	condition := &data.BaseMenuCondition{
		Types:  []int32{int32(common.BaseMenuType_FOLDER), int32(common.BaseMenuType_MENU), int32(common.BaseMenuType_EXT_LINK)},
		Status: int32(common.Status_ENABLE),
	}
	//是否超级管理员
	if baseRole.Code != _const.BaseRoleCode_Super {
		condition.Ids = _string.ConvertJsonStringToInt64Array(baseRole.Menus)
	}

	//用户权限
	var baseMenus []*models.BaseMenu
	baseMenus, err = s.baseMenuCase.List(ctx, condition)
	if err != nil {
		return nil, common.ErrorAccessForbidden("用户权限不存在")
	}

	return &admin.TreeRouteResponse{
		List: s.baseMenuCase.BuildRouteTree(baseMenus, 0),
	}, nil
}

// GetUserProfile
// 获取个人中心用户信息
func (s *AuthService) GetUserProfile(ctx context.Context, req *emptypb.Empty) (*admin.UserProfileForm, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	var baseUser *models.BaseUser
	baseUser, err = s.baseUserCase.GetFromID(ctx, authInfo.UserId)
	if err != nil {
		return nil, errors.New("用户不存在")
	}
	if baseUser.Status != int32(common.Status_ENABLE) {
		return nil, errors.New("用户状态错误")
	}
	// 查询角色信息
	var baseRole *models.BaseRole
	baseRole, err = s.baseRoleCase.GetFromID(ctx, baseUser.RoleID)
	if err != nil {
		return nil, errors.New("角色不存在")
	}
	// 查询部门信息
	var baseDept *models.BaseDept
	baseDept, err = s.baseDeptCase.GetFromID(ctx, baseUser.DeptID)
	if err != nil {
		return nil, errors.New("部门不存在")
	}
	return &admin.UserProfileForm{
		UserName:  baseUser.UserName,
		NickName:  baseUser.NickName,
		Avatar:    baseUser.Avatar,
		Gender:    baseUser.Gender,
		Phone:     baseUser.Phone,
		RoleName:  baseRole.Name,
		DeptName:  baseDept.Name,
		CreatedAt: _time.TimeToTimeString(baseUser.CreatedAt),
	}, nil
}

// UpdateUserProfile
// 修改个人中心用户信息
func (s *AuthService) UpdateUserProfile(ctx context.Context, req *admin.UserProfileForm) (*emptypb.Empty, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	var oldBaseUser *models.BaseUser
	oldBaseUser, err = s.baseUserCase.GetFromID(ctx, authInfo.UserId)
	if err != nil {
		log.Error("UpdateUserProfile err:", err.Error())
		return nil, errors.New("修改个人中心用户信息失败")
	}

	baseUser := &models.BaseUser{
		ID:       oldBaseUser.ID,
		UserName: req.UserName,
		NickName: req.NickName,
		Avatar:   req.Avatar,
		Gender:   req.Gender,
		Phone:    req.Phone,
	}
	err = s.baseUserCase.UpdateByID(ctx, baseUser)
	if err != nil {
		log.Error("UpdateUserProfile err:", err.Error())
		return nil, errors.New("修改个人中心用户信息失败")
	}
	// 删除图片
	return &emptypb.Empty{}, nil
}

// SendUpdatePhoneCode
// 发送手机号验证码
func (s *AuthService) SendUpdatePhoneCode(ctx context.Context, req *admin.SendUpdatePhoneCodeForm) (*emptypb.Empty, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}
	code := _string.GetRandomString(6)
	log.Errorf("code: %s", code)
	err = sdk.Runtime.GetCache().Set(fmt.Sprintf("%s:%d", _const.CacheKeyUpdatePhoneCode, authInfo.UserId), code, time.Minute*5)
	if err != nil {
		log.Error("SendUpdatePhoneCode err:", err.Error())
		return nil, errors.New("发送手机号验证码错误")
	}
	return &emptypb.Empty{}, nil
}

// UpdateUserPhone
// 修改个人中心手机号
func (s *AuthService) UpdateUserPhone(ctx context.Context, req *admin.UpdatePhoneForm) (*emptypb.Empty, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}
	var code string
	code, err = sdk.Runtime.GetCache().Get(fmt.Sprintf("%s:%d", _const.CacheKeyUpdatePhoneCode, authInfo.UserId))
	if err != nil {
		return nil, errors.New("验证码错误")
	}
	if code != req.Code {
		return nil, errors.New("验证码错误")
	}

	user := &models.BaseUser{
		ID:    authInfo.UserId,
		Phone: req.Phone,
	}
	err = s.baseUserCase.UpdateByID(ctx, user)
	if err != nil {
		log.Error("UpdateUserPhone err:", err.Error())
		return nil, errors.New("修改个人中心手机号失败")
	}

	return &emptypb.Empty{}, nil
}

// UpdateUserPwd
// 修改个人中心密码
func (s *AuthService) UpdateUserPwd(ctx context.Context, req *admin.UpdatePwdForm) (*emptypb.Empty, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败")
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	var baseUser *models.BaseUser
	baseUser, err = s.baseUserCase.GetFromID(ctx, authInfo.UserId)
	if err != nil {
		return nil, errors.New("用户不存在")
	}
	if req.GetNewPwd() != req.GetConfirmPwd() {
		return nil, errors.New("两次密码不一致")
	}
	err = crypto.Verify(req.GetOldPwd(), baseUser.Password)
	if err != nil {
		log.Errorf("verify pwd err: %s", err.Error())
		return nil, errors.New("旧密码错误")
	}

	password := s.baseUserCase.GetPassword(req.GetNewPwd())
	err = s.baseUserCase.UpdateByID(ctx, &models.BaseUser{
		ID:       baseUser.ID,
		Password: password,
	})
	if err != nil {
		log.Error("UpdateUserPwd err:", err.Error())
		return nil, errors.New("重置密码失败")
	}
	return &emptypb.Empty{}, nil
}
