// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_menu.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseMenuService is the server API for BaseMenuService service implement.
type BaseMenuService struct {
	admin.UnimplementedBaseMenuServiceServer
	baseMenuCase   *biz.BaseMenuCase
	casbinRuleCase *biz.CasbinRuleCase
}

// NewBaseMenuService create a service implement.
// Admin菜单管理服务
func NewBaseMenuService(
	ctx *bootstrap.Context,
	menuCase *biz.BaseMenuCase,
	casbinRuleCase *biz.CasbinRuleCase,
) *BaseMenuService {
	var ss = BaseMenuService{baseMenuCase: menuCase,
		casbinRuleCase: casbinRuleCase,
	}
	log.Debug("NewBaseMenuService.")
	return &ss
}

// TreeBaseMenu
// 查询菜单树形列表
func (s *BaseMenuService) TreeBaseMenu(ctx context.Context, req *emptypb.Empty) (*admin.TreeBaseMenuResponse, error) {
	tree, err := s.baseMenuCase.Tree(ctx, &data.BaseMenuCondition{})
	if err != nil {
		log.Error("TreeBaseMenu err:", err.Error())
		return nil, errors.New("查询菜单树形列表失败")
	}
	return tree, nil
}

// OptionBaseMenu
// 查询菜单树形选择
func (s *BaseMenuService) OptionBaseMenu(ctx context.Context, req *admin.OptionBaseMenuRequest) (*common.TreeOptionResponse, error) {
	tree, err := s.baseMenuCase.Option(ctx, &data.BaseMenuCondition{
		ParentId: req.ParentId,
	})
	if err != nil {
		log.Error("OptionBaseMenu err:", err.Error())
		return nil, errors.New("查询菜单树形选择失败")
	}
	return tree, nil
}

// GetBaseMenu
// 查询菜单
func (s *BaseMenuService) GetBaseMenu(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseMenuForm, error) {
	baseMenu, err := s.baseMenuCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseMenu err:", err.Error())
		return nil, errors.New("查询菜单失败")
	}
	return s.baseMenuCase.ConvertToProto(baseMenu), nil
}

// CreateBaseMenu
// 创建菜单
func (s *BaseMenuService) CreateBaseMenu(ctx context.Context, req *admin.BaseMenuForm) (*emptypb.Empty, error) {
	baseMenu := s.baseMenuCase.ConvertToModel(req)
	if baseMenu.Type == int32(common.BaseMenuType_FOLDER) {
		baseMenu.Component = "Layout"
	}
	err := s.baseMenuCase.Create(ctx, baseMenu)
	if err != nil {
		log.Error("CreateBaseMenu err:", err.Error())
		return nil, errors.New("创建菜单失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateBaseMenu
// 更新菜单
func (s *BaseMenuService) UpdateBaseMenu(ctx context.Context, req *admin.BaseMenuForm) (*emptypb.Empty, error) {
	err := s.baseMenuCase.Update(ctx, req)
	if err != nil {
		log.Error("UpdateBaseMenu err:", err.Error())
		return nil, errors.New("更新菜单失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteBaseMenu
// 删除菜单
func (s *BaseMenuService) DeleteBaseMenu(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.baseMenuCase.Delete(ctx, req.GetValue())
	if err != nil {
		log.Error("DeleteBaseMenu err:", err.Error())
		return nil, errors.New("删除菜单失败")
	}
	return &emptypb.Empty{}, nil
}

// SetBaseMenuStatus
// 设置状态
func (s *BaseMenuService) SetBaseMenuStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	// 查询下级
	id := req.GetId()
	count, err := s.baseMenuCase.Count(ctx, &data.BaseMenuCondition{
		ParentId: &id,
	})
	if err != nil {
		log.Error("SetBaseMenuStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	if count > 0 {
		return nil, errors.New("设置状态失败,下面有菜单")
	}
	err = s.baseMenuCase.UpdateByID(ctx, &models.BaseMenu{
		ID:     id,
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetBaseMenuStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
