// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_job.proto

package admin

import (
	"context"
	"errors"
	"time"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	"github.com/liujitcn/go-utils/str"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	_const "github.com/liujitcn/shop-admin/server/internal/const"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseJobService is the server API for BaseJobService service implement.
type BaseJobService struct {
	admin.UnimplementedBaseJobServiceServer
	*core.ShopCore
	baseJobCase    *biz.BaseJobCase
	baseJobLogCase *biz.BaseJobLogCase
}

// NewBaseJobService create a service implement.
// Admin定时任务服务
func NewBaseJobService(
	sc *core.ShopCore,
	baseJobCase *biz.BaseJobCase,
	baseJobLogCase *biz.BaseJobLogCase,
) *BaseJobService {
	var ss = BaseJobService{
		ShopCore:       sc,
		baseJobCase:    baseJobCase,
		baseJobLogCase: baseJobLogCase,
	}

	// 注册定时任务日志队列
	ss.Queue.Register(_const.JobLog, ss.baseJobLogCase.SaveJobLog)
	
	// 启动定时任务
	err := baseJobCase.Init(ss.Ctx.Context())
	if err != nil {
		log.Errorf("Init jobCase error: %s", err.Error())
	}

	log.Debug("NewBaseJobService.")
	return &ss
}

// PageBaseJob
// 查询定时任务分页列表
func (s *BaseJobService) PageBaseJob(ctx context.Context, req *admin.PageBaseJobRequest) (*admin.PageBaseJobResponse, error) {
	page, err := s.baseJobCase.Page(ctx, req)
	if err != nil {
		log.Error("PageBaseJob err:", err.Error())
		return nil, errors.New("查询定时任务分页列表失败")
	}
	return page, nil
}

// GetBaseJob
// 查询定时任务
func (s *BaseJobService) GetBaseJob(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseJobForm, error) {
	baseJob, err := s.baseJobCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseJob err:", err.Error())
		return nil, errors.New("查询定时任务失败")
	}
	return s.baseJobCase.ConvertToProto(baseJob), nil
}

// CreateBaseJob
// 创建定时任务
func (s *BaseJobService) CreateBaseJob(ctx context.Context, req *admin.BaseJobForm) (*emptypb.Empty, error) {
	baseJob := s.baseJobCase.ConvertToModel(req)
	err := s.baseJobCase.Create(ctx, baseJob)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("调用目标重复")
			}
		}
		log.Error("CreateBaseJob err:", err.Error())
		return nil, errors.New("创建定时任务失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateBaseJob
// 更新定时任务
func (s *BaseJobService) UpdateBaseJob(ctx context.Context, req *admin.BaseJobForm) (*emptypb.Empty, error) {
	baseJob := s.baseJobCase.ConvertToModel(req)
	err := s.baseJobCase.UpdateByID(ctx, baseJob)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("调用目标重复")
			}
		}
		log.Error("CreateBaseJob err:", err.Error())
		return nil, errors.New("更新定时任务失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteBaseJob
// 删除定时任务
func (s *BaseJobService) DeleteBaseJob(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := str.ConvertStringToInt64Array(req.GetValue())
	err := s.baseJobCase.Delete(ctx, ids)
	if err != nil {
		log.Error("Delete err:", err.Error())
		return nil, errors.New("删除定时任务失败")
	}
	return &emptypb.Empty{}, nil
}

// SetBaseJobStatus
// 设置状态
func (s *BaseJobService) SetBaseJobStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.baseJobCase.UpdateByID(ctx, &models.BaseJob{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetRoleStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}

// StartBaseJob
// 启动任务
func (s *BaseJobService) StartBaseJob(ctx context.Context, req *admin.StartBaseJobRequest) (*emptypb.Empty, error) {
	baseJob, err := s.baseJobCase.GetFromID(ctx, req.GetId())
	if err != nil {
		log.Error("StartBaseJob err:", err.Error())
		return nil, errors.New("启动任务失败")
	}
	err = s.baseJobCase.Start(ctx, baseJob)
	if err != nil {
		log.Error("StartBaseJob err:", err.Error())
		return nil, errors.New("启动任务失败")
	}
	return &emptypb.Empty{}, nil
}

// StopBaseJob
// 停止任务
func (s *BaseJobService) StopBaseJob(ctx context.Context, req *admin.StopBaseJobRequest) (*emptypb.Empty, error) {
	baseJob, err := s.baseJobCase.GetFromID(ctx, req.GetId())
	if err != nil {
		log.Error("StopBaseJob err:", err.Error())
		return nil, errors.New("停止任务失败")
	}
	cn := s.baseJobCase.Stop(baseJob.EntryID)

	select {
	case res := <-cn:
		if res {
			err = s.baseJobCase.CleanEntryId(ctx, baseJob.EntryID)
			if err != nil {
				log.Error("StopBaseJob err:", err.Error())
				return nil, errors.New("停止任务失败")
			}
		}
	case <-time.After(time.Second * 1):
		return nil, errors.New("操作超时！")
	}
	return &emptypb.Empty{}, nil
}

// ExecBaseJob
// 执行任务
func (s *BaseJobService) ExecBaseJob(ctx context.Context, req *admin.ExecBaseJobRequest) (*emptypb.Empty, error) {
	baseJob, err := s.baseJobCase.GetFromID(ctx, req.GetId())
	if err != nil {
		log.Error("ExecBaseJob err:", err.Error())
		return nil, errors.New("执行任务失败")
	}
	err = s.baseJobCase.Exec(ctx, baseJob)
	if err != nil {
		log.Error("ExecBaseJob err:", err.Error())
		return nil, errors.New("执行任务失败")
	}
	return &emptypb.Empty{}, nil
}

// PageBaseJobLog
// 查询定时任务日志分页列表
func (s *BaseJobService) PageBaseJobLog(ctx context.Context, req *admin.PageBaseJobLogRequest) (*admin.PageBaseJobLogResponse, error) {
	page, err := s.baseJobLogCase.Page(ctx, req)
	if err != nil {
		log.Error("PageBaseJobLog err:", err.Error())
		return nil, errors.New("查询定时任务日志分页列表失败")
	}

	return page, nil
}

// GetBaseJobLog
// 查询定时任务日志
func (s *BaseJobService) GetBaseJobLog(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseJobLog, error) {
	baseLog, err := s.baseJobLogCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseJobLog err:", err.Error())
		return nil, errors.New("查询定时任务日志失败")
	}

	return s.baseJobLogCase.ConvertToProto(baseLog), nil
}
