// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_api.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseApiService is the server API for BaseApiService service implement.
type BaseApiService struct {
	admin.UnimplementedBaseApiServiceServer
	baseApiCase *biz.BaseApiCase
}

// NewBaseApiService create a service implement.
// AdminAPI列表
func NewBaseApiService(
	ctx *bootstrap.Context,
	baseApiCase *biz.BaseApiCase,
) (*BaseApiService, error) {
	var ss = BaseApiService{baseApiCase: baseApiCase}
	// 注册API队列
	// 检查API
	err := ss.baseApiCase.ApiCheck()
	if err != nil {
		return nil, err
	}
	log.Debug("NewBaseApiService.")
	return &ss, nil
}

// ListBaseApi
// 查询API列表
func (s *BaseApiService) ListBaseApi(ctx context.Context, req *emptypb.Empty) (*admin.ListBaseApiResponse, error) {
	list, err := s.baseApiCase.List(ctx)
	if err != nil {
		log.Error("ListBaseApi err:", err.Error())
		return nil, errors.New("查询API列表失败")
	}

	return list, nil
}
