// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_log.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	_const "github.com/liujitcn/shop-admin/server/internal/const"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	baseCore "github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseLogService is the server API for BaseLogService service implement.
type BaseLogService struct {
	admin.UnimplementedBaseLogServiceServer
	*baseCore.ShopCore
	baseLogCase *biz.BaseLogCase
}

// NewBaseLogService create a service implement.
// Admin日志服务
func NewBaseLogService(
	sc *baseCore.ShopCore,
	logCase *biz.BaseLogCase,
) *BaseLogService {
	var ss = BaseLogService{
		ShopCore:    sc,
		baseLogCase: logCase}
	// 注册日志队列
	ss.Queue.Register(string(_const.Log), ss.baseLogCase.SaveLog)
	log.Debug("NewBaseLogService.")
	return &ss
}

// PageBaseLog
// 查询日志分页列表
func (s *BaseLogService) PageBaseLog(ctx context.Context, req *admin.PageBaseLogRequest) (*admin.PageBaseLogResponse, error) {
	page, err := s.baseLogCase.Page(ctx, req)
	if err != nil {
		log.Error("PageBaseLog err:", err.Error())
		return nil, errors.New("查询日志分页列表失败")
	}

	return page, nil
}

// GetBaseLog
// 查询日志
func (s *BaseLogService) GetBaseLog(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseLog, error) {
	baseLog, err := s.baseLogCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseLog err:", err.Error())
		return nil, errors.New("查询日志失败")
	}

	return s.baseLogCase.ConvertToProto(baseLog), nil
}
