// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_config.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	"github.com/golang/protobuf/ptypes/empty"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/kratos-kit/sdk"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	_const "github.com/liujitcn/shop-admin/server/internal/const"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseConfigService is the server API for BaseConfigService service implement.
type BaseConfigService struct {
	admin.UnimplementedBaseConfigServiceServer
	*core.ShopCore
	baseConfigCase *biz.BaseConfigCase
}

// NewBaseConfigService create a service implement.
// Admin系统配置服务
func NewBaseConfigService(
	sc *core.ShopCore,
	configCase *biz.BaseConfigCase,
) (*BaseConfigService, error) {
	var ss = BaseConfigService{
		ShopCore:       sc,
		baseConfigCase: configCase}
	// 服务启动，刷新缓存
	_, err := ss.RefreshBaseConfig(context.Background(), &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	log.Debug("NewBaseConfigService.")
	return &ss, nil
}

// RefreshBaseConfig
// 刷新缓存
func (s *BaseConfigService) RefreshBaseConfig(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	// 只刷新系统内置缓存
	list, err := s.baseConfigCase.List(ctx, &data.BaseConfigCondition{
		Site: 1,
	})
	if err != nil {
		log.Error("RefreshBaseConfig err:", err.Error())
		return nil, errors.New("刷新缓存失败")
	}
	for _, config := range list {
		err = sdk.Runtime.GetCache().Set(_const.CacheKeyConfig+config.Key, config.Value, -1)
		if err != nil {
			log.Error("RefreshBaseConfig err:", err.Error())
			return nil, errors.New("刷新缓存失败")
		}
	}

	return &emptypb.Empty{}, nil
}

// PageBaseConfig
// 查询系统配置分页列表
func (s *BaseConfigService) PageBaseConfig(ctx context.Context, req *admin.PageBaseConfigRequest) (*admin.PageBaseConfigResponse, error) {
	page, err := s.baseConfigCase.Page(ctx, req)
	if err != nil {
		log.Error("PageBaseConfig err:", err.Error())
		return nil, errors.New("查询系统配置分页列表失败")
	}

	return page, nil
}

// GetBaseConfig
// 查询系统配置
func (s *BaseConfigService) GetBaseConfig(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseConfigForm, error) {
	config, err := s.baseConfigCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseConfig err:", err.Error())
		return nil, errors.New("查询系统配置失败")
	}

	return s.baseConfigCase.ConvertToProto(config), nil
}

// CreateBaseConfig
// 创建系统配置
func (s *BaseConfigService) CreateBaseConfig(ctx context.Context, req *admin.BaseConfigForm) (*emptypb.Empty, error) {
	config := s.baseConfigCase.ConvertToModel(req)
	err := s.baseConfigCase.Create(ctx, config)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("配置key重复")
			}
		}
		log.Error("CreateBaseConfig err:", err.Error())
		return nil, errors.New("创建系统配置失败")
	}
	err = sdk.Runtime.GetCache().Set(_const.CacheKeyConfig+config.Key, config.Value, -1)
	if err != nil {
		log.Error("CreateBaseConfig err:", err.Error())
		return nil, errors.New("刷新缓存失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateBaseConfig
// 更新系统配置
func (s *BaseConfigService) UpdateBaseConfig(ctx context.Context, req *admin.BaseConfigForm) (*emptypb.Empty, error) {
	config := s.baseConfigCase.ConvertToModel(req)
	err := s.baseConfigCase.UpdateByID(ctx, config)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("配置key重复")
			}
		}
		log.Error("UpdateBaseConfig err:", err.Error())
		return nil, errors.New("更新系统配置失败")
	}
	err = sdk.Runtime.GetCache().Set(_const.CacheKeyConfig+config.Key, config.Value, -1)
	if err != nil {
		log.Error("UpdateBaseConfig err:", err.Error())
		return nil, errors.New("刷新缓存失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteBaseConfig
// 删除系统配置
func (s *BaseConfigService) DeleteBaseConfig(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	list, err := s.baseConfigCase.List(ctx, &data.BaseConfigCondition{
		Ids: ids,
	})
	if err != nil {
		log.Error("DeleteBaseConfig err:", err.Error())
		return nil, errors.New("删除系统配置失败")
	}
	err = s.baseConfigCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteBaseConfig err:", err.Error())
		return nil, errors.New("删除系统配置失败")
	}
	for _, config := range list {
		err = sdk.Runtime.GetCache().Del(_const.CacheKeyConfig + config.Key)
		if err != nil {
			log.Error("DeleteBaseConfig err:", err.Error())
			return nil, errors.New("刷新缓存失败")
		}
	}
	return &emptypb.Empty{}, nil
}

// SetBaseConfigStatus
// 设置状态
func (s *BaseConfigService) SetBaseConfigStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.baseConfigCase.UpdateByID(ctx, &models.BaseConfig{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetBaseConfigStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	var config *models.BaseConfig
	config, err = s.baseConfigCase.GetFromID(ctx, req.GetId())
	if err != nil {
		log.Error("SetBaseConfigStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	if config.Status == int32(common.Status_ENABLE) {
		err = sdk.Runtime.GetCache().Set(_const.CacheKeyConfig+config.Key, config.Value, -1)
		if err != nil {
			log.Error("SetBaseConfigStatus err:", err.Error())
			return nil, errors.New("刷新缓存失败")
		}
	} else {
		err = sdk.Runtime.GetCache().Del(_const.CacheKeyConfig + config.Key)
		if err != nil {
			log.Error("SetBaseConfigStatus err:", err.Error())
			return nil, errors.New("刷新缓存失败")
		}
	}
	return &empty.Empty{}, nil
}
