// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_dept.proto

package admin

import (
	"context"
	"errors"
	"fmt"

	"github.com/go-kratos/kratos/v2/log"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseDeptService is the server API for BaseDeptService service implement.
type BaseDeptService struct {
	admin.UnimplementedBaseDeptServiceServer
	*core.ShopCore
	baseDeptCase *biz.BaseDeptCase
}

// NewBaseDeptService create a service implement.
// Admin部门服务
func NewBaseDeptService(
	sc *core.ShopCore,
	deptCase *biz.BaseDeptCase,
) *BaseDeptService {
	var ss = BaseDeptService{
		ShopCore:     sc,
		baseDeptCase: deptCase}
	log.Debug("NewBaseDeptService.")
	return &ss
}

// TreeBaseDept
// 查询部门树形列表
func (s *BaseDeptService) TreeBaseDept(ctx context.Context, req *emptypb.Empty) (*admin.TreeBaseDeptResponse, error) {
	tree, err := s.baseDeptCase.Tree(ctx, &data.BaseDeptCondition{})
	if err != nil {
		log.Error("TreeBaseDept err:", err.Error())
		return nil, errors.New("查询部门树形列表失败")
	}

	return tree, nil
}

// OptionBaseDept
// 查询部门树形选择
func (s *BaseDeptService) OptionBaseDept(ctx context.Context, req *admin.OptionBaseDeptRequest) (*common.TreeOptionResponse, error) {
	tree, err := s.baseDeptCase.Option(ctx, &data.BaseDeptCondition{
		ParentId: req.ParentId,
	})
	if err != nil {
		log.Error("OptionBaseDept err:", err.Error())
		return nil, errors.New("查询部门树形选择失败")
	}
	return tree, nil
}

// GetBaseDept
// 查询部门
func (s *BaseDeptService) GetBaseDept(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseDeptForm, error) {
	baseDept, err := s.baseDeptCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseDept err:", err.Error())
		return nil, errors.New("查询部门失败")
	}

	return s.baseDeptCase.ConvertToProto(baseDept), nil
}

// CreateBaseDept
// 创建部门
func (s *BaseDeptService) CreateBaseDept(ctx context.Context, req *admin.BaseDeptForm) (*emptypb.Empty, error) {
	baseDept := s.baseDeptCase.ConvertToModel(req)
	err := s.baseDeptCase.Create(ctx, baseDept)
	if err != nil {
		log.Error("CreateBaseDept err:", err.Error())
		return nil, errors.New("创建部门失败")
	}
	// 查询当前父节点，更新path
	path := fmt.Sprintf("/0/%d", baseDept.ID)
	parentId := req.GetParentId()
	if parentId != 0 {
		var parentDept *models.BaseDept
		parentDept, err = s.baseDeptCase.GetFromID(ctx, parentId)
		if err != nil {
			return nil, errors.New("创建部门失败，更新路径错误")
		}
		path = fmt.Sprintf("%s/%d", parentDept.Path, baseDept.ID)
	}
	baseDept.Path = path
	err = s.baseDeptCase.UpdateByID(ctx, baseDept)
	if err != nil {
		log.Error("CreateBaseDept err:", err.Error())
		return nil, errors.New("创建部门失败，更新路径错误")
	}
	return &emptypb.Empty{}, nil
}

// UpdateBaseDept
// 更新部门
func (s *BaseDeptService) UpdateBaseDept(ctx context.Context, req *admin.BaseDeptForm) (*emptypb.Empty, error) {
	baseDept := s.baseDeptCase.ConvertToModel(req)
	err := s.baseDeptCase.UpdateByID(ctx, baseDept)
	if err != nil {
		log.Error("UpdateBaseDept err:", err.Error())
		return nil, errors.New("更新部门失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteBaseDept
// 删除部门
func (s *BaseDeptService) DeleteBaseDept(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	for _, id := range ids {
		// 查询下级
		count, err := s.baseDeptCase.Count(ctx, &data.BaseDeptCondition{
			ParentId: &id,
		})
		if err != nil {
			log.Error("DeleteBaseDept err:", err.Error())
			return nil, errors.New("删除部门失败")
		}
		if count > 0 {
			return nil, errors.New("删除部门失败,下面有部门")
		}
	}
	err := s.baseDeptCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteBaseDept err:", err.Error())
		return nil, errors.New("删除部门失败")
	}
	return &emptypb.Empty{}, nil
}

// SetBaseDeptStatus
// 设置状态
func (s *BaseDeptService) SetBaseDeptStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	// 查询下级
	id := req.GetId()
	count, err := s.baseDeptCase.Count(ctx, &data.BaseDeptCondition{
		ParentId: &id,
	})
	if err != nil {
		log.Error("SetBaseDeptStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	if count > 0 {
		return nil, errors.New("设置状态失败,下面有部门")
	}

	err = s.baseDeptCase.UpdateByID(ctx, &models.BaseDept{
		ID:     id,
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetBaseDeptStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
