// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_role.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	_const "github.com/liujitcn/shop-admin/server/internal/const"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseRoleService is the server API for BaseRoleService service implement.
type BaseRoleService struct {
	admin.UnimplementedBaseRoleServiceServer
	baseRoleCase *biz.BaseRoleCase
}

// NewBaseRoleService create a service implement.
// Admin角色管理服务
func NewBaseRoleService(
	ctx *bootstrap.Context,
	roleCase *biz.BaseRoleCase,
) *BaseRoleService {
	var ss = BaseRoleService{baseRoleCase: roleCase}
	log.Debug("NewBaseRoleService.")
	return &ss
}

// OptionBaseRole
// 查询角色下拉选择
func (s *BaseRoleService) OptionBaseRole(ctx context.Context, req *emptypb.Empty) (*common.SelectOptionResponse, error) {
	list, err := s.baseRoleCase.List(ctx, &data.BaseRoleCondition{})
	if err != nil {
		log.Error("OptionBaseRole err:", err.Error())
		return nil, errors.New("查询角色下拉列表失败")
	}

	options := make([]*common.SelectOptionResponse_Option, 0)
	for _, item := range list {
		options = append(options, &common.SelectOptionResponse_Option{
			Label: item.Name,
			Value: item.ID,
		})
	}

	return &common.SelectOptionResponse{
		List: options,
	}, nil
}

// PageBaseRole
// 查询角色分页列表
func (s *BaseRoleService) PageBaseRole(ctx context.Context, req *admin.PageBaseRoleRequest) (*admin.PageBaseRoleResponse, error) {
	page, err := s.baseRoleCase.Page(ctx, req)
	if err != nil {
		log.Error("PageBaseRole err:", err.Error())
		return nil, errors.New("查询角色分页列表失败")
	}
	return page, nil
}

// GetBaseRole
// 查询角色
func (s *BaseRoleService) GetBaseRole(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseRoleForm, error) {
	baseRole, err := s.baseRoleCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseRole err:", err.Error())
		return nil, errors.New("查询角色失败")
	}
	return s.baseRoleCase.ConvertToProto(baseRole), nil
}

// CreateBaseRole
// 创建角色
func (s *BaseRoleService) CreateBaseRole(ctx context.Context, req *admin.BaseRoleForm) (*emptypb.Empty, error) {
	err := s.baseRoleCase.Create(ctx, req)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("角色编号重复")
			}
		}
		log.Error("CreateBaseRole err:", err.Error())
		return nil, errors.New("创建角色失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateBaseRole
// 更新角色
func (s *BaseRoleService) UpdateBaseRole(ctx context.Context, req *admin.BaseRoleForm) (*emptypb.Empty, error) {
	err := s.baseRoleCase.Update(ctx, req)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("角色编号重复")
			}
		}
		log.Error("CreateBaseRole err:", err.Error())
		return nil, errors.New("创建角色失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteBaseRole
// 删除角色
func (s *BaseRoleService) DeleteBaseRole(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	err := s.baseRoleCase.Delete(ctx, req.GetValue())
	if err != nil {
		log.Error("Delete err:", err.Error())
		return nil, errors.New("删除角色失败")
	}
	return &emptypb.Empty{}, nil
}

// SetBaseRoleStatus
// 设置状态
func (s *BaseRoleService) SetBaseRoleStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	baseRoleOld, err := s.baseRoleCase.GetFromID(ctx, req.GetId())
	if err != nil {
		log.Error("SetRoleStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	if baseRoleOld.Code == _const.BaseRoleCode_Super {
		return nil, errors.New("设置状态失败，不能操作超级管理员角色")
	}
	err = s.baseRoleCase.UpdateByID(ctx, &models.BaseRole{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetRoleStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}

// SetBaseRoleMenus
// 设置角色菜单权限
func (s *BaseRoleService) SetBaseRoleMenus(ctx context.Context, req *admin.SetMenusRequest) (*emptypb.Empty, error) {
	err := s.baseRoleCase.SetBaseRoleMenus(ctx, req)
	if err != nil {
		log.Error("SetRoleMenus err:", err.Error())
		return nil, errors.New("设置角色菜单权限失败")
	}
	return &emptypb.Empty{}, nil
}
