// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/dashboard.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	baseCore "github.com/liujitcn/shop-base/server/core"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// DashboardService is the server API for DashboardService service implement.
type DashboardService struct {
	admin.UnimplementedDashboardServiceServer
	*baseCore.ShopCore
	dashboardCase *biz.DashboardCase
}

// NewDashboardService create a service implement.
// Admin首页服务
func NewDashboardService(
	sc *baseCore.ShopCore,
	dashboardCase *biz.DashboardCase,
) *DashboardService {
	var ss = DashboardService{
		ShopCore:      sc,
		dashboardCase: dashboardCase}
	log.Debug("NewDashboardService.")
	return &ss
}

// DashboardCountUser
// 查询汇总数据（用户）
func (s *DashboardService) DashboardCountUser(ctx context.Context, req *admin.DashboardCountRequest) (*admin.DashboardCountResponse, error) {
	res, err := s.dashboardCase.DashboardCountUser(ctx, req)
	if err != nil {
		log.Error("DashboardCountUser err:", err.Error())
		return nil, errors.New("查询汇总数据（用户）失败")
	}
	return res, nil
}

// DashboardCountGoods
// 查询汇总数据（商品）
func (s *DashboardService) DashboardCountGoods(ctx context.Context, req *admin.DashboardCountRequest) (*admin.DashboardCountResponse, error) {
	res, err := s.dashboardCase.DashboardCountGoods(ctx, req)
	if err != nil {
		log.Error("DashboardCountGoods err:", err.Error())
		return nil, errors.New("查询汇总数据（商品）失败")
	}
	return res, nil
}

// DashboardCountOrder
// 查询汇总数据（订单）
func (s *DashboardService) DashboardCountOrder(ctx context.Context, req *admin.DashboardCountRequest) (*admin.DashboardCountResponse, error) {
	res, err := s.dashboardCase.DashboardCountOrder(ctx, req)
	if err != nil {
		log.Error("DashboardCountOrder err:", err.Error())
		return nil, errors.New("查询汇总数据（订单）失败")
	}
	return res, nil
}

// DashboardCountSale
// 查询汇总数据（销量）
func (s *DashboardService) DashboardCountSale(ctx context.Context, req *admin.DashboardCountRequest) (*admin.DashboardCountResponse, error) {
	res, err := s.dashboardCase.DashboardCountSale(ctx, req)
	if err != nil {
		log.Error("DashboardCountSale err:", err.Error())
		return nil, errors.New("查询汇总数据（销量）失败")
	}
	return res, nil
}

// DashboardBarOrder
// 查询订单销量（柱状图）
func (s *DashboardService) DashboardBarOrder(ctx context.Context, req *admin.DashboardBarOrderRequest) (*admin.DashboardBarResponse, error) {
	res, err := s.dashboardCase.DashboardBarOrder(ctx, req)
	if err != nil {
		log.Error("DashboardBarOrder err:", err.Error())
		return nil, errors.New("查询订单销量（柱状图）失败")
	}
	return res, nil
}

// DashboardBarGoods
// 查询商品销量（柱状图）
func (s *DashboardService) DashboardBarGoods(ctx context.Context, req *admin.DashboardBarGoodsRequest) (*admin.DashboardBarResponse, error) {
	res, err := s.dashboardCase.DashboardBarGoods(ctx, req)
	if err != nil {
		log.Error("DashboardBarGoods err:", err.Error())
		return nil, errors.New("查询商品销量（柱状图）失败")
	}
	return res, nil
}

// DashboardPieGoods
// 查询商品分类（饼状图）
func (s *DashboardService) DashboardPieGoods(ctx context.Context, req *admin.DashboardPieGoodsRequest) (*admin.DashboardPieResponse, error) {
	res, err := s.dashboardCase.DashboardPieGoods(ctx, req)
	if err != nil {
		log.Error("DashboardPieGoods err:", err.Error())
		return nil, errors.New("查询商品分类（饼状图）失败")
	}
	return res, nil
}

// DashboardRadarOrder
// 查询商品订单销量状态（雷达图）
func (s *DashboardService) DashboardRadarOrder(ctx context.Context, req *admin.DashboardRadarOrderRequest) (*admin.DashboardRadarResponse, error) {
	res, err := s.dashboardCase.DashboardRadarOrder(ctx, req)
	if err != nil {
		log.Error("DashboardRadarOrder err:", err.Error())
		return nil, errors.New("查询商品订单销量状态（雷达图）失败")
	}
	return res, nil
}
