// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/goods_spec.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsSpecService is the server API for GoodsSpecService service implement.
type GoodsSpecService struct {
	admin.UnimplementedGoodsSpecServiceServer
	goodsSpecCase *biz.GoodsSpecCase
}

// NewGoodsSpecService create a service implement.
// Admin商品规格服务
func NewGoodsSpecService(
	ctx *bootstrap.Context,
	goodsSpecCase *biz.GoodsSpecCase,
) *GoodsSpecService {
	var ss = GoodsSpecService{goodsSpecCase: goodsSpecCase}
	log.Debug("NewGoodsSpecService.")
	return &ss
}

// ListGoodsSpec
// 查询商品规格列表
func (s *GoodsSpecService) ListGoodsSpec(ctx context.Context, req *admin.ListGoodsSpecRequest) (*admin.ListGoodsSpecResponse, error) {
	list, err := s.goodsSpecCase.ListByGoodsId(ctx, req.GetGoodsId())
	if err != nil {
		log.Error("ListSpec err:", err.Error())
		return nil, errors.New("查询规格列表失败")
	}
	return &admin.ListGoodsSpecResponse{
		List: list,
	}, nil
}
