// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/goods_prop.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	"github.com/liujitcn/go-utils/str"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsPropService is the server API for GoodsPropService service implement.
type GoodsPropService struct {
	admin.UnimplementedGoodsPropServiceServer
	goodsPropCase *biz.GoodsPropCase
}

// NewGoodsPropService create a service implement.
// Admin商品属性服务
func NewGoodsPropService(
	ctx *bootstrap.Context,
	goodsPropCase *biz.GoodsPropCase,
) *GoodsPropService {
	var ss = GoodsPropService{goodsPropCase: goodsPropCase}
	log.Debug("NewGoodsPropService.")
	return &ss
}

// PageGoodsProp
// 查询商品属性分页列表
func (s *GoodsPropService) PageGoodsProp(ctx context.Context, req *admin.PageGoodsPropRequest) (*admin.PageGoodsPropResponse, error) {
	page, err := s.goodsPropCase.Page(ctx, req)
	if err != nil {
		log.Error("PageGoodsProp err:", err.Error())
		return nil, errors.New("查询属性列表失败")
	}

	return page, nil
}

// GetGoodsProp
// 查询商品属性
func (s *GoodsPropService) GetGoodsProp(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsProp, error) {
	goodsProp, err := s.goodsPropCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetGoodsProp err:", err.Error())
		return nil, errors.New("查询商品属性失败")
	}

	return s.goodsPropCase.ConvertToProto(goodsProp), nil
}

// CreateGoodsProp
// 创建商品属性
func (s *GoodsPropService) CreateGoodsProp(ctx context.Context, req *admin.GoodsProp) (*emptypb.Empty, error) {
	goodsProp := s.goodsPropCase.ConvertToModel(req)
	err := s.goodsPropCase.Create(ctx, goodsProp)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("商品属性标签重复")
			}
		}
		log.Error("CreateGoodsProp err:", err.Error())
		return nil, errors.New("创建商品属性失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateGoodsProp
// 更新商品属性
func (s *GoodsPropService) UpdateGoodsProp(ctx context.Context, req *admin.GoodsProp) (*emptypb.Empty, error) {
	goodsProp := s.goodsPropCase.ConvertToModel(req)
	err := s.goodsPropCase.UpdateByID(ctx, goodsProp)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("商品属性标签重复")
			}
		}
		log.Error("UpdateGoodsProp err:", err.Error())
		return nil, errors.New("更新商品属性失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteGoodsProp
// 删除商品属性
func (s *GoodsPropService) DeleteGoodsProp(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := str.ConvertStringToInt64Array(req.GetValue())
	err := s.goodsPropCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteGoodsProp err:", err.Error())
		return nil, errors.New("删除商品属性失败")
	}
	return &emptypb.Empty{}, nil
}
