// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/goods_category.proto

package admin

import (
	"context"
	"errors"
	"fmt"

	"github.com/go-kratos/kratos/v2/log"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	baseCore "github.com/liujitcn/shop-base/server/core"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsCategoryService is the server API for GoodsCategoryService service implement.
type GoodsCategoryService struct {
	admin.UnimplementedGoodsCategoryServiceServer
	*baseCore.ShopCore
	goodsCategoryCase *biz.GoodsCategoryCase
}

// NewGoodsCategoryService create a service implement.
// Admin分类服务
func NewGoodsCategoryService(
	sc *baseCore.ShopCore,
	categoryCase *biz.GoodsCategoryCase,
) *GoodsCategoryService {
	var ss = GoodsCategoryService{
		ShopCore:          sc,
		goodsCategoryCase: categoryCase}
	log.Debug("NewGoodsCategoryService.")
	return &ss
}

// TreeGoodsCategory
// 查询分类树形列表
func (s *GoodsCategoryService) TreeGoodsCategory(ctx context.Context, req *emptypb.Empty) (*admin.TreeGoodsCategoryResponse, error) {
	tree, err := s.goodsCategoryCase.Tree(ctx, &data.GoodsCategoryCondition{})
	if err != nil {
		log.Error("TreeGoodsCategory err:", err.Error())
		return nil, errors.New("查询分类树形列表失败")
	}

	return tree, nil
}

// OptionGoodsCategory
// 查询分类树形选择
func (s *GoodsCategoryService) OptionGoodsCategory(ctx context.Context, req *admin.OptionGoodsCategoryRequest) (*common.TreeOptionResponse, error) {
	tree, err := s.goodsCategoryCase.Option(ctx, &data.GoodsCategoryCondition{
		ParentId: req.ParentId,
	})
	if err != nil {
		log.Error("OptionGoodsCategory err:", err.Error())
		return nil, errors.New("查询分类树形选择失败")
	}
	return tree, nil
}

// GetGoodsCategory
// 查询分类
func (s *GoodsCategoryService) GetGoodsCategory(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsCategoryForm, error) {
	goodsCategory, err := s.goodsCategoryCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetGoodsCategory err:", err.Error())
		return nil, errors.New("查询分类失败")
	}

	return s.goodsCategoryCase.ConvertToProto(goodsCategory), nil
}

// CreateGoodsCategory
// 创建分类
func (s *GoodsCategoryService) CreateGoodsCategory(ctx context.Context, req *admin.GoodsCategoryForm) (*emptypb.Empty, error) {
	goodsCategory := s.goodsCategoryCase.ConvertToModel(req)
	err := s.goodsCategoryCase.Create(ctx, goodsCategory)
	if err != nil {
		log.Error("CreateGoodsCategory err:", err.Error())
		return nil, errors.New("创建分类失败")
	}

	// 查询当前父节点，更新path
	path := fmt.Sprintf("/0/%d", goodsCategory.ID)
	parentId := req.GetParentId()
	if parentId != 0 {
		var parentCategory *models.GoodsCategory
		parentCategory, err = s.goodsCategoryCase.GetFromID(ctx, parentId)
		if err != nil {
			return nil, errors.New("创建分类失败，更新路径错误")
		}
		path = fmt.Sprintf("%s/%d", parentCategory.Path, goodsCategory.ID)
	}
	goodsCategory.Path = path
	err = s.goodsCategoryCase.UpdateByID(ctx, goodsCategory)
	if err != nil {
		return nil, errors.New("创建分类失败，更新路径错误")
	}
	return &emptypb.Empty{}, nil
}

// UpdateGoodsCategory
// 更新分类
func (s *GoodsCategoryService) UpdateGoodsCategory(ctx context.Context, req *admin.GoodsCategoryForm) (*emptypb.Empty, error) {
	goodsCategory := s.goodsCategoryCase.ConvertToModel(req)
	err := s.goodsCategoryCase.UpdateByID(ctx, goodsCategory)
	if err != nil {
		log.Error("UpdateGoodsCategory err:", err.Error())
		return nil, errors.New("更新分类失败")
	}
	// 删除图片
	return &emptypb.Empty{}, nil
}

// DeleteGoodsCategory
// 删除分类
func (s *GoodsCategoryService) DeleteGoodsCategory(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	for _, id := range ids {
		// 查询下级
		count, err := s.goodsCategoryCase.Count(ctx, &data.GoodsCategoryCondition{
			ParentId: &id,
		})
		if err != nil {
			log.Error("DeleteGoodsCategory err:", err.Error())
			return nil, errors.New("删除分类失败")
		}
		if count > 0 {
			return nil, errors.New("删除分类失败,下面有分类")
		}
	}
	oldGoodsCategoryList, err := s.goodsCategoryCase.FindAll(ctx, &data.GoodsCategoryCondition{
		Ids: ids,
	})
	if err != nil {
		log.Error("UpdateGoodsCategory err:", err.Error())
		return nil, errors.New("更新分类失败")
	}
	err = s.goodsCategoryCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteGoodsCategory err:", err.Error())
		return nil, errors.New("删除分类失败")
	}
	// 删除图片
	oldFile := make([]string, 0)
	for _, item := range oldGoodsCategoryList {
		oldFile = append(oldFile, item.Picture)
	}
	return &emptypb.Empty{}, nil
}

// SetGoodsCategoryStatus
// 设置状态
func (s *GoodsCategoryService) SetGoodsCategoryStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	// 查询下级
	id := req.GetId()
	count, err := s.goodsCategoryCase.Count(ctx, &data.GoodsCategoryCondition{
		ParentId: &id,
	})
	if err != nil {
		log.Error("SetGoodsCategoryStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	if count > 0 {
		return nil, errors.New("设置状态失败,下面有分类")
	}

	err = s.goodsCategoryCase.UpdateByID(ctx, &models.GoodsCategory{
		ID:     id,
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetGoodsCategoryStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
