// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/goods_sku.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsSkuService is the server API for GoodsSkuService service implement.
type GoodsSkuService struct {
	admin.UnimplementedGoodsSkuServiceServer
	*core.ShopCore
	goodsSkuCase *biz.GoodsSkuCase
}

// NewGoodsSkuService create a service implement.
// Admin商品SKU服务
func NewGoodsSkuService(sc *core.ShopCore, goodsSkuCase *biz.GoodsSkuCase) *GoodsSkuService {
	var ss = GoodsSkuService{
		ShopCore: sc,
		goodsSkuCase: goodsSkuCase}
	log.Debug("NewGoodsSkuService.")
	return &ss
}

// PageGoodsSku
// 查询商品SKU分页列表
func (s *GoodsSkuService) PageGoodsSku(ctx context.Context, req *admin.PageGoodsSkuRequest) (*admin.PageGoodsSkuResponse, error) {
	page, err := s.goodsSkuCase.Page(ctx, req)
	if err != nil {
		log.Error("PageGoodsSku err:", err.Error())
		return nil, errors.New("查询商品SKU分页列表失败")
	}
	return page, nil
}

// GetGoodsSku
// 查询商品SKU
func (s *GoodsSkuService) GetGoodsSku(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsSku, error) {
	goodsSku, err := s.goodsSkuCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetGoodsSku err:", err.Error())
		return nil, errors.New("查询商品SKU失败")
	}

	return s.goodsSkuCase.ConvertToProto(goodsSku), nil
}

// UpdateGoodsSku
// 更新商品SKU
func (s *GoodsSkuService) UpdateGoodsSku(ctx context.Context, req *admin.GoodsSku) (*emptypb.Empty, error) {
	goodsSku := s.goodsSkuCase.ConvertToModel(req)
	err := s.goodsSkuCase.UpdateByID(ctx, goodsSku)
	if err != nil {
		log.Error("UpdateGoodsSku err:", err.Error())
		return nil, errors.New("更新商品SKU失败")
	}
	return &emptypb.Empty{}, nil
}
