// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/goods.proto

package admin

import (
	"context"
	"errors"
	"strings"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	baseCore "github.com/liujitcn/shop-base/server/core"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// GoodsService is the server API for GoodsService service implement.
type GoodsService struct {
	admin.UnimplementedGoodsServiceServer
	*baseCore.ShopCore
	goodsCase         *biz.GoodsCase
	goodsCategoryCase *biz.GoodsCategoryCase
}

// NewGoodsService create a service implement.
// Admin商品服务
func NewGoodsService(
	sc *baseCore.ShopCore,
	infoCase *biz.GoodsCase,
	categoryCase *biz.GoodsCategoryCase,
) *GoodsService {
	var ss = GoodsService{
		ShopCore:          sc,
		goodsCase:         infoCase,
		goodsCategoryCase: categoryCase,
	}
	log.Debug("NewGoodsService.")
	return &ss
}

// ListGoods
// 查询商品列表
func (s *GoodsService) ListGoods(ctx context.Context, req *admin.ListGoodsRequest) (*admin.ListGoodsResponse, error) {
	categoryNameMap := s.goodsCategoryCase.NameMap(ctx, &data.GoodsCategoryCondition{})
	all, err := s.goodsCase.FindAll(ctx, &data.GoodsCondition{
		Name:   req.GetName(),
		Status: int32(common.Status_ENABLE),
	})
	if err != nil {
		log.Error("ListGoods err:", err.Error())
		return nil, errors.New("查询商品列表失败")
	}
	list := make([]*admin.ListGoodsResponse_Goods, 0)
	for _, item := range all {
		g := &admin.ListGoodsResponse_Goods{
			Id:    item.ID,
			Name:  item.Name,
			Price: item.Price,
		}
		if categoryName, ok := categoryNameMap[item.CategoryID]; ok {
			g.CategoryName = categoryName
		}
		list = append(list, g)
	}

	return &admin.ListGoodsResponse{
		List: list,
	}, nil
}

// PageGoods
// 查询商品分页列表
func (s *GoodsService) PageGoods(ctx context.Context, req *admin.PageGoodsRequest) (*admin.PageGoodsResponse, error) {
	page, err := s.goodsCase.Page(ctx, req)
	if err != nil {
		log.Error("PageGoods err:", err.Error())
		return nil, errors.New("查询商品分页列表失败")
	}

	return page, nil
}

// GetGoods
// 查询商品
func (s *GoodsService) GetGoods(ctx context.Context, req *wrapperspb.Int64Value) (*admin.GoodsForm, error) {
	goods, err := s.goodsCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetGoods err:", err.Error())
		return nil, errors.New("查询商品失败")
	}

	return goods, nil
}

// CreateGoods
// 创建商品
func (s *GoodsService) CreateGoods(ctx context.Context, req *admin.GoodsForm) (*emptypb.Empty, error) {
	err := s.goodsCase.Create(ctx, req)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				msg := errMySQL.Message
				if strings.Contains(msg, models.TableNameGoods) {
					return nil, errors.New("商品编号重复")
				}
				if strings.Contains(msg, models.TableNameGoodsProp) {
					return nil, errors.New("商品属性重复")
				}
				if strings.Contains(msg, models.TableNameGoodsSKU) {
					return nil, errors.New("规格编号重复")
				}
			}
		}
		return nil, errors.New("创建商品失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateGoods
// 更新商品
func (s *GoodsService) UpdateGoods(ctx context.Context, req *admin.GoodsForm) (*emptypb.Empty, error) {
	err := s.goodsCase.Update(ctx, req)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				msg := errMySQL.Message
				if strings.Contains(msg, models.TableNameGoods) {
					return nil, errors.New("商品编号重复")
				}
				if strings.Contains(msg, models.TableNameGoodsProp) {
					return nil, errors.New("商品属性重复")
				}
				if strings.Contains(msg, models.TableNameGoodsSKU) {
					return nil, errors.New("规格编号重复")
				}
			}
		}
		log.Error("UpdateGoods err:", err.Error())
		return nil, errors.New("更新商品失败")
	}
	// 删除图片
	return &emptypb.Empty{}, nil
}

// DeleteGoods
// 删除商品
func (s *GoodsService) DeleteGoods(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	oldGoodsList, err := s.goodsCase.FindAll(ctx, &data.GoodsCondition{
		Ids: ids,
	})
	err = s.goodsCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteGoods err:", err.Error())
		return nil, errors.New("删除商品失败")
	}
	// 删除图片
	oldFile := make([]string, 0)
	for _, item := range oldGoodsList {
		banner := _string.ConvertJsonStringToStringArray(item.Banner)
		oldFile = append(oldFile, banner...)
		detail := _string.ConvertJsonStringToStringArray(item.Detail)
		oldFile = append(oldFile, detail...)
	}
	return &emptypb.Empty{}, nil
}

// SetGoodsStatus
// 设置状态
func (s *GoodsService) SetGoodsStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.goodsCase.UpdateByID(ctx, &models.Goods{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetGoodsStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
