// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/order.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// OrderService is the server API for OrderService service implement.
type OrderService struct {
	admin.UnimplementedOrderServiceServer
	orderCase *biz.OrderCase
}

// NewOrderService create a service implement.
// 订单服务
func NewOrderService(
	ctx *bootstrap.Context,
	orderCase *biz.OrderCase,
) *OrderService {
	var ss = OrderService{orderCase: orderCase}
	log.Debug("NewOrderService.")
	return &ss
}

// PageOrder
// 查询订单分页列表
func (s *OrderService) PageOrder(ctx context.Context, req *admin.PageOrderRequest) (*admin.PageOrderResponse, error) {
	page, err := s.orderCase.Page(ctx, req)
	if err != nil {
		log.Error("PageOrder err:", err.Error())
		return nil, errors.New("查询订单分页列表失败")
	}
	return page, nil
}

// GetOrder
// 查询订单
func (s *OrderService) GetOrder(ctx context.Context, req *wrapperspb.Int64Value) (*admin.OrderResponse, error) {
	res, err := s.orderCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetOrder err:", err.Error())
		return nil, errors.New("查询订单失败")
	}

	return res, nil
}

// GetOrderRefund
// 查询订单退款信息
func (s *OrderService) GetOrderRefund(ctx context.Context, req *wrapperspb.Int64Value) (*admin.OrderRefundResponse, error) {
	res, err := s.orderCase.GetOrderRefund(ctx, req.GetValue())
	if err != nil {
		log.Error("GetOrderRefund err:", err.Error())
		return nil, errors.New("查询订单退款信息失败")
	}

	return res, nil
}

// RefundOrder
// 订单退款
func (s *OrderService) RefundOrder(ctx context.Context, req *admin.RefundOrderRequest) (*emptypb.Empty, error) {
	err := s.orderCase.RefundOrder(ctx, req)
	if err != nil {
		log.Error("RefundOrder err:", err.Error())
		return nil, errors.New("订单退款失败")
	}

	return &emptypb.Empty{}, nil
}

// GetOrderShipped
// 查询订单发货信息
func (s *OrderService) GetOrderShipped(ctx context.Context, req *wrapperspb.Int64Value) (*admin.OrderShippedResponse, error) {
	res, err := s.orderCase.GetOrderShipped(ctx, req.GetValue())
	if err != nil {
		log.Error("GetOrderShipped err:", err.Error())
		return nil, errors.New("查询订单发货信息失败")
	}

	return res, nil
}

// ShippedOrder
// 订单发货
func (s *OrderService) ShippedOrder(ctx context.Context, req *admin.ShippedOrderRequest) (*emptypb.Empty, error) {
	err := s.orderCase.ShippedOrder(ctx, req)
	if err != nil {
		log.Error("ShippedOrder err:", err.Error())
		return nil, errors.New("订单发货失败")
	}

	return &emptypb.Empty{}, nil
}
