// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/pay_bill.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// PayBillService is the server API for PayBillService service implement.
type PayBillService struct {
	admin.UnimplementedPayBillServiceServer
	payBillCase *biz.PayBillCase
}

// NewPayBillService create a service implement.
// Admin支付账单服务
func NewPayBillService(
	ctx *bootstrap.Context,
	payBillCase *biz.PayBillCase,
) *PayBillService {
	var ss = PayBillService{payBillCase: payBillCase}
	log.Debug("NewPayBillService.")
	return &ss
}

// PagePayBill
// 查询支付账单分页列表
func (s *PayBillService) PagePayBill(ctx context.Context, req *admin.PagePayBillRequest) (*admin.PagePayBillResponse, error) {
	page, err := s.payBillCase.Page(ctx, req)
	if err != nil {
		log.Error("PagePayBill err:", err.Error())
		return nil, errors.New("查询支付账单分页列表失败")
	}
	return page, nil
}
