// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/shop_service.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopServiceService is the server API for ShopServiceService service implement.
type ShopServiceService struct {
	admin.UnimplementedShopServiceServiceServer
	*core.ShopCore
	serviceCase *biz.ShopServiceCase
}

// NewShopServiceService create a service implement.
// Admin商城服务
func NewShopServiceService(
	sc *core.ShopCore,
	serviceCase *biz.ShopServiceCase,
) *ShopServiceService {
	var ss = ShopServiceService{
		ShopCore:    sc,
		serviceCase: serviceCase}
	log.Debug("NewShopServiceService.")
	return &ss
}

// PageShopService
// 查询商城服务分页列表
func (s *ShopServiceService) PageShopService(ctx context.Context, req *admin.PageShopServiceRequest) (*admin.PageShopServiceResponse, error) {
	page, err := s.serviceCase.Page(ctx, req)
	if err != nil {
		log.Error("PageShopService err:", err.Error())
		return nil, errors.New("查询商城服务分页列表失败")
	}

	return page, nil
}

// GetShopService
// 查询商城服务
func (s *ShopServiceService) GetShopService(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopServiceForm, error) {
	shopService, err := s.serviceCase.Find(ctx, &data.ShopServiceCondition{
		Id: req.GetValue(),
	})
	if err != nil {
		log.Error("GetShopService err:", err.Error())
		return nil, errors.New("查询商城服务失败")
	}

	return s.serviceCase.ConvertToProto(shopService), nil
}

// CreateShopService
// 创建商城服务
func (s *ShopServiceService) CreateShopService(ctx context.Context, req *admin.ShopServiceForm) (*emptypb.Empty, error) {
	shopService := s.serviceCase.ConvertToModel(req)
	err := s.serviceCase.Create(ctx, shopService)
	if err != nil {
		log.Error("CreateShopService err:", err.Error())
		return nil, errors.New("创建商城服务失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateShopService
// 更新商城服务
func (s *ShopServiceService) UpdateShopService(ctx context.Context, req *admin.ShopServiceForm) (*emptypb.Empty, error) {
	shopService := s.serviceCase.ConvertToModel(req)
	err := s.serviceCase.UpdateByID(ctx, shopService)
	if err != nil {
		log.Error("UpdateShopService err:", err.Error())
		return nil, errors.New("更新商城服务失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteShopService
// 删除商城服务
func (s *ShopServiceService) DeleteShopService(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	err := s.serviceCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteShopService err:", err.Error())
		return nil, errors.New("删除商城服务失败")
	}
	return &emptypb.Empty{}, nil
}

// SetShopServiceStatus
// 设置状态
func (s *ShopServiceService) SetShopServiceStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.serviceCase.UpdateByID(ctx, &models.ShopService{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetShopServiceStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
