// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/shop_banner.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	baseCore "github.com/liujitcn/shop-base/server/core"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopBannerService is the server API for ShopBannerService service implement.
type ShopBannerService struct {
	admin.UnimplementedShopBannerServiceServer
	*baseCore.ShopCore
	bannerCase *biz.ShopBannerCase
}

// NewShopBannerService create a service implement.
// Admin轮播图服务
func NewShopBannerService(
	sc *baseCore.ShopCore,
	bannerCase *biz.ShopBannerCase,
) *ShopBannerService {
	var ss = ShopBannerService{
		ShopCore:   sc,
		bannerCase: bannerCase}
	log.Debug("NewShopBannerService.")
	return &ss
}

// PageShopBanner
// 查询轮播图分页列表
func (s *ShopBannerService) PageShopBanner(ctx context.Context, req *admin.PageShopBannerRequest) (*admin.PageShopBannerResponse, error) {
	page, err := s.bannerCase.Page(ctx, req)
	if err != nil {
		log.Error("PageShopBanner err:", err.Error())
		return nil, errors.New("查询轮播图分页列表失败")
	}

	return page, nil
}

// GetShopBanner
// 查询轮播图
func (s *ShopBannerService) GetShopBanner(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopBannerForm, error) {
	shopBanner, err := s.bannerCase.Find(ctx, &data.ShopBannerCondition{
		Id: req.GetValue(),
	})
	if err != nil {
		log.Error("GetShopBanner err:", err.Error())
		return nil, errors.New("查询轮播图失败")
	}

	return s.bannerCase.ConvertToProto(shopBanner), nil
}

// CreateShopBanner
// 创建轮播图
func (s *ShopBannerService) CreateShopBanner(ctx context.Context, req *admin.ShopBannerForm) (*emptypb.Empty, error) {
	shopBanner := s.bannerCase.ConvertToModel(req)
	err := s.bannerCase.Create(ctx, shopBanner)
	if err != nil {
		log.Error("CreateShopBanner err:", err.Error())
		return nil, errors.New("创建轮播图失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateShopBanner
// 更新轮播图
func (s *ShopBannerService) UpdateShopBanner(ctx context.Context, req *admin.ShopBannerForm) (*emptypb.Empty, error) {
	shopBanner := s.bannerCase.ConvertToModel(req)
	err := s.bannerCase.UpdateByID(ctx, shopBanner)
	if err != nil {
		log.Error("UpdateShopBanner err:", err.Error())
		return nil, errors.New("更新轮播图失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteShopBanner
// 删除轮播图
func (s *ShopBannerService) DeleteShopBanner(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	oldShopBannerList, err := s.bannerCase.FindAll(ctx, &data.ShopBannerCondition{
		Ids: ids,
	})
	if err != nil {
		log.Error("DeleteShopBanner err:", err.Error())
		return nil, errors.New("删除轮播图失败")
	}
	err = s.bannerCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteShopBanner err:", err.Error())
		return nil, errors.New("删除轮播图失败")
	}
	// 删除图片
	oldFile := make([]string, 0)
	for _, item := range oldShopBannerList {
		oldFile = append(oldFile, item.Picture)
	}
	return &emptypb.Empty{}, nil
}

// SetShopBannerStatus
// 设置状态
func (s *ShopBannerService) SetShopBannerStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.bannerCase.UpdateByID(ctx, &models.ShopBanner{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetShopBannerStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
