// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/shop_hot.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-sql-driver/mysql"
	_string "github.com/liujitcn/go-utils/string"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/core"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-gorm-gen/models"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopHotService is the server API for ShopHotService service implement.
type ShopHotService struct {
	admin.UnimplementedShopHotServiceServer
	*core.ShopCore
	hotCase     *biz.ShopHotCase
	hotItemCase *biz.ShopHotItemCase
}

// NewShopHotService create a service implement.
// Admin商城热门推荐服务
func NewShopHotService(
	sc *core.ShopCore,
	hotCase *biz.ShopHotCase,
	hotItemCase *biz.ShopHotItemCase,
) *ShopHotService {
	var ss = ShopHotService{
		ShopCore:    sc,
		hotCase:     hotCase,
		hotItemCase: hotItemCase,
	}
	log.Debug("NewShopHotService.")
	return &ss
}

// PageShopHot
// 查询商城热门推荐分页列表
func (s *ShopHotService) PageShopHot(ctx context.Context, req *admin.PageShopHotRequest) (*admin.PageShopHotResponse, error) {
	page, err := s.hotCase.Page(ctx, req)
	if err != nil {
		log.Error("PageShopHot err:", err.Error())
		return nil, errors.New("查询商城热门推荐分页列表失败")
	}

	return page, nil
}

// GetShopHot
// 查询商城热门推荐
func (s *ShopHotService) GetShopHot(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopHotForm, error) {
	shopHot, err := s.hotCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetShopHot err:", err.Error())
		return nil, errors.New("查询商城热门推荐失败")
	}

	return s.hotCase.ConvertToProto(shopHot), nil
}

// CreateShopHot
// 创建商城热门推荐
func (s *ShopHotService) CreateShopHot(ctx context.Context, req *admin.ShopHotForm) (*emptypb.Empty, error) {
	shopHot := s.hotCase.ConvertToModel(req)
	err := s.hotCase.Create(ctx, shopHot)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("商城热门推荐重复")
			}
		}
		log.Error("CreateShopHot err:", err.Error())
		return nil, errors.New("创建商城热门推荐失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateShopHot
// 更新商城热门推荐
func (s *ShopHotService) UpdateShopHot(ctx context.Context, req *admin.ShopHotForm) (*emptypb.Empty, error) {
	shopHot := s.hotCase.ConvertToModel(req)
	err := s.hotCase.UpdateByID(ctx, shopHot)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("商城热门推荐重复")
			}
		}
		log.Error("UpdateShopHot err:", err.Error())
		return nil, errors.New("更新商城热门推荐失败")
	}
	// 删除图片
	return &emptypb.Empty{}, nil
}

// DeleteShopHot
// 删除商城热门推荐
func (s *ShopHotService) DeleteShopHot(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	oldShopHotList, err := s.hotCase.FindAll(ctx, &data.ShopHotCondition{
		Ids: ids,
	})
	if err != nil {
		log.Error("DeleteShopHot err:", err.Error())
		return nil, errors.New("删除商城热门推荐失败")
	}
	for _, id := range ids {
		// 查询
		var hot *models.ShopHot
		hot, err = s.hotCase.GetFromID(ctx, id)
		if err != nil {
			log.Error("DeleteShopHot err:", err.Error())
			return nil, errors.New("删除商城热门推荐失败")
		}
		// 查询属性
		var count int64
		count, err = s.hotItemCase.Count(ctx, &data.ShopHotItemCondition{
			HotId: hot.ID,
		})
		if err != nil {
			log.Error("DeleteShopHot err:", err.Error())
			return nil, errors.New("删除商城热门推荐失败")
		}
		if count > 0 {
			return nil, errors.New("删除商城热门推荐失败,下面有内容")
		}
	}
	err = s.hotCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteShopHot err:", err.Error())
		return nil, errors.New("删除商城热门推荐失败")
	}
	// 删除图片
	oldFile := make([]string, 0)
	for _, item := range oldShopHotList {
		picture := _string.ConvertJsonStringToStringArray(item.Picture)
		oldFile = append(oldFile, picture...)
		oldFile = append(oldFile, item.Banner)
	}
	return &emptypb.Empty{}, nil
}

// SetShopHotStatus
// 设置状态
func (s *ShopHotService) SetShopHotStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.hotCase.UpdateByID(ctx, &models.ShopHot{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetShopHotStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}

// PageShopHotItem
// 查询商城热门推荐属性分页列表
func (s *ShopHotService) PageShopHotItem(ctx context.Context, req *admin.PageShopHotItemRequest) (*admin.PageShopHotItemResponse, error) {
	page, err := s.hotItemCase.Page(ctx, req)
	if err != nil {
		log.Error("PageShopHotItem err:", err.Error())
		return nil, errors.New("查询热门推荐选项分页列表失败")
	}
	return page, nil
}

// GetShopHotItem
// 查询商城热门推荐属性
func (s *ShopHotService) GetShopHotItem(ctx context.Context, req *wrapperspb.Int64Value) (*admin.ShopHotItemForm, error) {
	shopHotItem, err := s.hotItemCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetShopHotItem err:", err.Error())
		return nil, errors.New("查询热门推荐选项失败")
	}
	return shopHotItem, nil
}

// CreateShopHotItem
// 创建商城热门推荐属性
func (s *ShopHotService) CreateShopHotItem(ctx context.Context, req *admin.ShopHotItemForm) (*emptypb.Empty, error) {
	err := s.hotItemCase.Create1(ctx, req)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("热门推荐选项重复")
			}
		}
		log.Error("CreateShopHotItem err:", err.Error())
		return nil, errors.New("创建热门推荐选项失败")
	}
	return &emptypb.Empty{}, nil
}

// UpdateShopHotItem
// 更新商城热门推荐属性
func (s *ShopHotService) UpdateShopHotItem(ctx context.Context, req *admin.ShopHotItemForm) (*emptypb.Empty, error) {
	err := s.hotItemCase.Update(ctx, req)
	if err != nil {
		if errMySQL, ok := errors.AsType[*mysql.MySQLError](err); ok {
			switch errMySQL.Number {
			case 1062:
				return nil, errors.New("热门推荐选项重复")
			}
		}
		log.Error("UpdateShopHotItem err:", err.Error())
		return nil, errors.New("更新热门推荐选项失败")
	}
	return &emptypb.Empty{}, nil
}

// DeleteShopHotItem
// 删除商城热门推荐属性
func (s *ShopHotService) DeleteShopHotItem(ctx context.Context, req *wrapperspb.StringValue) (*emptypb.Empty, error) {
	ids := _string.ConvertStringToInt64Array(req.GetValue())
	err := s.hotItemCase.Delete(ctx, ids)
	if err != nil {
		log.Error("DeleteShopHotItem err:", err.Error())
		return nil, errors.New("删除热门推荐选项失败")
	}
	return &emptypb.Empty{}, nil
}

// SetShopHotItemStatus
// 设置状态
func (s *ShopHotService) SetShopHotItemStatus(ctx context.Context, req *common.SetStatusRequest) (*emptypb.Empty, error) {
	err := s.hotItemCase.UpdateByID(ctx, &models.ShopHotItem{
		ID:     req.GetId(),
		Status: req.GetStatus(),
	})
	if err != nil {
		log.Error("SetShopHotItemStatus err:", err.Error())
		return nil, errors.New("设置状态失败")
	}
	return &emptypb.Empty{}, nil
}
