// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/user_store.proto

package admin

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// UserStoreService is the server API for UserStoreService service implement.
type UserStoreService struct {
	admin.UnimplementedUserStoreServiceServer
	log           *log.Helper
	userStoreCase *biz.UserStoreCase
}

// NewUserStoreService create a service implement.
// Admin用户门店管理服务
func NewUserStoreService(
	ctx *bootstrap.Context,
	userStoreCase *biz.UserStoreCase,
) *UserStoreService {
	var ss = UserStoreService{userStoreCase: userStoreCase}
	log.Debug("NewUserStoreService.")
	return &ss
}

// PageUserStore
// 查询用户门店列表
func (s *UserStoreService) PageUserStore(ctx context.Context, req *admin.PageUserStoreRequest) (*admin.PageUserStoreResponse, error) {
	page, err := s.userStoreCase.Page(ctx, req)
	if err != nil {
		log.Error("PageUserStore err:", err.Error())
		return nil, errors.New("查询用户门店列表失败")
	}

	return page, nil
}

// GetUserStore
// 查询用户门店
func (s *UserStoreService) GetUserStore(ctx context.Context, req *wrapperspb.Int64Value) (*admin.UserStore, error) {
	userStore, err := s.userStoreCase.GetUserStore(ctx, req.GetValue())
	if err != nil {
		log.Error("GetUserStore err:", err.Error())
		return nil, errors.New("查询用户门店失败")
	}

	return userStore, nil
}

// AuditUserStore
// 门店认证
func (s *UserStoreService) AuditUserStore(ctx context.Context, req *admin.AuditUserStoreForm) (*emptypb.Empty, error) {
	err := s.userStoreCase.AuditUserStore(ctx, req)
	if err != nil {
		log.Error("AuditUserStore err:", err.Error())
		return nil, errors.New("门店认证失败")
	}
	return &emptypb.Empty{}, nil
}
