// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: app/shop_service.proto

package app

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/shop-admin/server/api/gen/go/app"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/service/app/biz"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// ShopServiceService is the server API for ShopServiceService service implement.
type ShopServiceService struct {
	app.UnimplementedShopServiceServiceServer
	serviceCase *biz.ShopServiceCase
}

// NewShopServiceService create a service implement.
// App商城服务
func NewShopServiceService(
	ctx *bootstrap.Context,
	serviceCase *biz.ShopServiceCase,
) *ShopServiceService {
	var ss = ShopServiceService{serviceCase: serviceCase}
	log.Debug("NewShopServiceService.")
	return &ss
}

// ListShopService
// 查询商城服务列表
func (s *ShopServiceService) ListShopService(ctx context.Context, req *emptypb.Empty) (*app.ListShopServiceResponse, error) {
	all, err := s.serviceCase.FindAll(ctx, &data.ShopServiceCondition{
		Status: int32(common.Status_ENABLE),
	})
	if err != nil {
		log.Error("ListShopService err:", err.Error())
		return nil, errors.New("查询商城服务列表失败")
	}
	list := make([]*app.ShopService, 0)
	for _, item := range all {
		list = append(list, s.serviceCase.ConvertToProto(ctx, item))
	}
	return &app.ListShopServiceResponse{
		List: list,
	}, nil
}
