// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: login/login.proto

package login

import (
	"context"
	"errors"

	"github.com/go-kratos/kratos/v2/log"
	"github.com/liujitcn/go-sdk/auth"
	authData "github.com/liujitcn/go-sdk/auth/data"
	"github.com/liujitcn/go-sdk/cache"
	"github.com/liujitcn/go-sdk/captcha"
	"github.com/liujitcn/shop-admin/server/api/gen/go/common"
	"github.com/liujitcn/shop-admin/server/api/gen/go/login"
	"github.com/tx7do/kratos-authn/engine"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

const _ = grpc.SupportPackageIsVersion7

// LoginService is the server API for LoginService service implement.
type LoginService struct {
	login.UnimplementedLoginServiceServer
	c         cache.Cache
	userToken *authData.UserToken
}

// NewLoginService create a service implement.
// 登录公共服务
func NewLoginService(
	ctx *bootstrap.Context,
	c cache.Cache,
	userToken *authData.UserToken,
) *LoginService {
	var ss = LoginService{c: c}
	log.Debug("NewLoginService.")
	return &ss
}

// Captcha
// 验证码
func (s *LoginService) Captcha(ctx context.Context, req *emptypb.Empty) (*login.CaptchaResponse, error) {
	id, b64s, err := captcha.DriverDigitFunc()
	if err != nil {
		return nil, err
	}
	return &login.CaptchaResponse{
		CaptchaId:     id,
		CaptchaBase64: b64s,
	}, err
}

// Logout
// 登出
func (s *LoginService) Logout(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}
	err = s.userToken.RemoveToken(authInfo.UserId)
	if err != nil {
		return nil, errors.New("退出登录失败")
	}
	return &emptypb.Empty{}, nil
}

// RefreshToken
// 刷新认证令牌
func (s *LoginService) RefreshToken(ctx context.Context, req *login.RefreshTokenRequest) (*login.LoginResponse, error) {
	authInfo, err := auth.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	// 校验刷新令牌
	refreshToken := s.userToken.GetRefreshToken(authInfo.UserId)
	if refreshToken != req.GetRefreshToken() {
		return nil, common.ErrorIncorrectRefreshToken("invalid refresh token")
	}

	// 生成新的访问令牌
	var accessToken string
	accessToken, err = s.userToken.GenerateAccessToken(authInfo)
	if err != nil {
		return nil, common.ErrorIncorrectRefreshToken("invalid refresh token")
	}
	// Token 有效期
	expiresIn := s.userToken.GetAccessTokenExpires()

	return &login.LoginResponse{
		TokenType:    engine.BearerWord,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    expiresIn,
	}, nil
}
