authn:
  jwt:
    secret: Shop@Server
    accessTokenExpires: 300000s
    refreshTokenExpires: 36000s
    whiteList:
      prefix:
      regex:
      path:
      match:
        - "/config.ConfigService/GetConfig"
        - "/login.LoginService/Captcha"
        - "/login.LoginService/Login"
        - "/pay.PayService/PayNotify"
