shop_admin_server:
  whiteList:
    match:
      - "/config.ConfigService/GetConfig"
      - "/login.LoginService/Captcha"
      - "/admin.AuthService/Login"
  wxPay:
    appid: xxx
    mchId: 'xxxx'
    notifyUrl: xxxx
    mchCertSn: xxxx
    mchCertPath: xxxx
    mchAPIv3Key: xxxx
