// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/database/gorm"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"
	"github.com/liujitcn/shop-admin/server/internal/configs"
	"github.com/liujitcn/shop-admin/server/internal/core"
	data2 "github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/middleware"
	"github.com/liujitcn/shop-admin/server/internal/server"
	"github.com/liujitcn/shop-admin/server/internal/service/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/task"
	"github.com/liujitcn/shop-admin/server/internal/service/app"
	biz3 "github.com/liujitcn/shop-admin/server/internal/service/app/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/config"
	biz4 "github.com/liujitcn/shop-admin/server/internal/service/config/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/file"
	biz5 "github.com/liujitcn/shop-admin/server/internal/service/file/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/login"
	"github.com/liujitcn/shop-admin/server/internal/service/pay"
	biz2 "github.com/liujitcn/shop-admin/server/internal/service/pay/biz"
	"github.com/liujitcn/shop-gorm-gen/data"
)

import (
	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"
	_ "github.com/liujitcn/kratos-kit/logger/zap"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	authentication_Jwt := configs.ParseAuthnJwt(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	confData, err := configs.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Database := configs.ParseDatabase(confData)
	client, cleanup, err := gorm.NewGormClient(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(client)
	baseUserRepo := data2.NewBaseUserRepo(dataData)
	baseDeptRepo := data2.NewBaseDeptRepo(dataData)
	baseUserCase := biz.NewBaseUserCase(baseUserRepo, baseDeptRepo)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Redis := configs.ParseRedis(confData)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	grpcMiddlewares := server.NewGrpcMiddleware(context, authenticator, baseUserCase, engine, userToken, authentication_Jwt)
	data_Queue := configs.ParseQueue(confData)
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	confPprof, err := configs.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(confPprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	shopCore, cleanup4, err := core.NewShopCore(context, cacheCache, queueQueue, client, pprofPprof, userToken)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	transaction := data.NewTransaction(dataData)
	baseRoleRepo := data2.NewBaseRoleRepo(dataData)
	casbinRuleRepo := data2.NewCasbinRuleRepo(dataData)
	baseMenuRepo := data2.NewBaseMenuRepo(dataData)
	baseApiRepo := data2.NewBaseApiRepo(dataData)
	baseApiCase := biz.NewBaseApiCase(baseApiRepo)
	casbinRuleCase, err := biz.NewCasbinRuleCase(casbinRuleRepo, baseMenuRepo, baseRoleRepo, baseApiCase, engine)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseRoleCase := biz.NewBaseRoleCase(transaction, baseRoleRepo, casbinRuleCase)
	baseDeptCase := biz.NewBaseDeptCase(baseDeptRepo)
	baseMenuCase := biz.NewBaseMenuCase(transaction, baseMenuRepo, casbinRuleCase)
	authService := admin.NewAuthService(shopCore, baseUserCase, baseRoleCase, baseDeptCase, baseMenuCase)
	baseApiService, err := admin.NewBaseApiService(shopCore, baseApiCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseConfigRepo := data2.NewBaseConfigRepo(dataData)
	baseConfigCase := biz.NewBaseConfigCase(baseConfigRepo)
	baseConfigService, err := admin.NewBaseConfigService(shopCore, baseConfigCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseDeptService := admin.NewBaseDeptService(shopCore, baseDeptCase)
	baseDictRepo := data2.NewBaseDictRepo(dataData)
	baseDictCase := biz.NewBaseDictCase(baseDictRepo)
	baseDictItemRepo := data2.NewBaseDictItemRepo(dataData)
	baseDictItemCase := biz.NewBaseDictItemCase(baseDictRepo, baseDictItemRepo)
	baseDictService := admin.NewBaseDictService(shopCore, baseDictCase, baseDictItemCase)
	baseJobRepo := data2.NewBaseJobRepo(dataData)
	confOSS, err := configs.ParseOss(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(confOSS)
	shopAdminServerConfig := configs.NewShopAdminServerConfig(context)
	wxPay, err := configs.ParseWxPay(shopAdminServerConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	wxPayCase, err := biz2.NewWxPayCase(wxPay)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	payBillRepo := data2.NewPayBillRepo(dataData)
	payBillCase := biz2.NewPayBillCase(payBillRepo)
	orderPaymentRepo := data2.NewOrderPaymentRepo(dataData)
	orderRefundRepo := data2.NewOrderRefundRepo(dataData)
	tradeBill := task.NewTradeBill(ossOSS, transaction, wxPayCase, payBillCase, orderPaymentRepo, orderRefundRepo)
	v := task.NewTaskList(tradeBill)
	baseJobCase := biz.NewBaseJobCase(baseJobRepo, v)
	baseJobLogRepo := data2.NewBaseJobLogRepo(dataData)
	baseJobLogCase := biz.NewBaseJobLogCase(baseJobLogRepo)
	baseJobService := admin.NewBaseJobService(shopCore, baseJobCase, baseJobLogCase)
	baseLogRepo := data2.NewBaseLogRepo(dataData)
	baseLogCase := biz.NewBaseLogCase(baseLogRepo)
	baseLogService := admin.NewBaseLogService(shopCore, baseLogCase)
	baseMenuService := admin.NewBaseMenuService(shopCore, baseMenuCase, casbinRuleCase)
	baseRoleService := admin.NewBaseRoleService(shopCore, baseRoleCase)
	baseUserService := admin.NewBaseUserService(shopCore, baseUserCase)
	goodsRepo := data2.NewGoodsRepo(dataData)
	goodsCategoryRepo := data2.NewGoodsCategoryRepo(dataData)
	goodsPropRepo := data2.NewGoodsPropRepo(dataData)
	goodsPropCase := biz.NewGoodsPropCase(goodsPropRepo)
	goodsSpecRepo := data2.NewGoodsSpecRepo(dataData)
	goodsSpecCase := biz.NewGoodsSpecCase(goodsSpecRepo)
	goodsSkuRepo := data2.NewGoodsSkuRepo(dataData)
	goodsSkuCase := biz.NewGoodsSkuCase(goodsSkuRepo)
	goodsCase := biz.NewGoodsCase(transaction, goodsRepo, goodsCategoryRepo, goodsPropCase, goodsSpecCase, goodsSkuCase)
	goodsCategoryCase := biz.NewGoodsCategoryCase(goodsCategoryRepo)
	orderAddressRepo := data2.NewOrderAddressRepo(dataData)
	orderAddressCase := biz.NewOrderAddressCase(orderAddressRepo)
	orderRepo := data2.NewOrderRepo(dataData)
	orderCancelRepo := data2.NewOrderCancelRepo(dataData)
	orderCancelCase := biz.NewOrderCancelCase(orderCancelRepo)
	orderGoodsRepo := data2.NewOrderGoodsRepo(dataData)
	orderGoodsCase := biz.NewOrderGoodsCase(orderGoodsRepo)
	orderLogisticsRepo := data2.NewOrderLogisticsRepo(dataData)
	orderLogisticsCase := biz.NewOrderLogisticsCase(orderLogisticsRepo)
	orderPaymentCase := biz.NewOrderPaymentCase(orderPaymentRepo)
	orderRefundCase := biz.NewOrderRefundCase(orderRefundRepo)
	orderCase := biz.NewOrderCase(transaction, orderAddressCase, orderRepo, orderCancelCase, orderGoodsCase, orderLogisticsCase, orderPaymentCase, orderRefundCase, baseUserCase, baseDictItemCase, wxPayCase)
	dashboardCase := biz.NewDashboardCase(baseUserCase, goodsCase, goodsCategoryCase, orderCase, orderGoodsCase, baseDictCase, baseDictItemCase)
	dashboardService := admin.NewDashboardService(shopCore, dashboardCase)
	goodsCategoryService := admin.NewGoodsCategoryService(shopCore, goodsCategoryCase)
	goodsService := admin.NewGoodsService(shopCore, goodsCase, goodsCategoryCase)
	goodsPropService := admin.NewGoodsPropService(shopCore, goodsPropCase)
	goodsSkuService := admin.NewGoodsSkuService(shopCore, goodsSkuCase)
	goodsSpecService := admin.NewGoodsSpecService(shopCore, goodsSpecCase)
	orderService := admin.NewOrderService(shopCore, orderCase)
	bizPayBillCase := biz.NewPayBillCase(payBillRepo)
	payBillService := admin.NewPayBillService(shopCore, bizPayBillCase)
	shopBannerRepo := data2.NewShopBannerRepo(dataData)
	shopBannerCase := biz.NewShopBannerCase(shopBannerRepo)
	shopBannerService := admin.NewShopBannerService(shopCore, shopBannerCase)
	shopHotRepo := data2.NewShopHotRepo(dataData)
	shopHotCase := biz.NewShopHotCase(shopHotRepo)
	shopHotItemRepo := data2.NewShopHotItemRepo(dataData)
	shopHotGoodsRepo := data2.NewShopHotGoodsRepo(dataData)
	shopHotItemCase := biz.NewShopHotItemCase(transaction, shopHotRepo, shopHotItemRepo, shopHotGoodsRepo)
	shopHotService := admin.NewShopHotService(shopCore, shopHotCase, shopHotItemCase)
	shopServiceRepo := data2.NewShopServiceRepo(dataData)
	shopServiceCase := biz.NewShopServiceCase(shopServiceRepo)
	shopServiceService := admin.NewShopServiceService(shopCore, shopServiceCase)
	userStoreRepo := data2.NewUserStoreRepo(dataData)
	baseAreaRepo := data2.NewBaseAreaRepo(dataData)
	baseAreaCase := biz.NewBaseAreaCase(baseAreaRepo)
	userStoreCase := biz.NewUserStoreCase(transaction, userStoreRepo, baseAreaCase, baseUserCase, baseRoleCase)
	userStoreService := admin.NewUserStoreService(shopCore, userStoreCase)
	bizShopServiceCase := biz3.NewShopServiceCase(shopServiceRepo)
	appShopServiceService := app.NewShopServiceService(shopCore, bizShopServiceCase)
	configCase := biz4.NewConfigCase(baseConfigRepo)
	configService := config.NewConfigService(shopCore, configCase)
	fileCase := biz5.NewFileCase(ossOSS)
	fileService := file.NewFileService(shopCore, fileCase)
	loginService := login.NewLoginService(shopCore)
	orderSchedulerCase := biz2.NewOrderSchedulerCase()
	payCase := biz2.NewPayCase(transaction, orderRepo, orderGoodsRepo, orderPaymentRepo, orderRefundRepo, orderSchedulerCase, wxPayCase)
	payService := pay.NewPayService(shopCore, payCase)
	grpcServer, err := server.NewGRPCServer(context, grpcMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, dashboardService, goodsCategoryService, goodsService, goodsPropService, goodsSkuService, goodsSpecService, orderService, payBillService, shopBannerService, shopHotService, shopServiceService, userStoreService, appShopServiceService, configService, fileService, loginService, payService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHttpMiddleware(context, authenticator, baseUserCase, engine, userToken, authentication_Jwt)
	httpServer, err := server.NewHttpServer(context, httpMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, dashboardService, goodsCategoryService, goodsService, goodsPropService, goodsSkuService, goodsSpecService, orderService, payBillService, shopBannerService, shopHotService, shopServiceService, userStoreService, appShopServiceService, configService, fileService, loginService, payService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kratosApp := newApp(context, grpcServer, httpServer)
	return kratosApp, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
