// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/liujitcn/kratos-kit/bootstrap"
	"github.com/liujitcn/kratos-kit/cache"
	"github.com/liujitcn/kratos-kit/database/gorm"
	"github.com/liujitcn/kratos-kit/oss"
	"github.com/liujitcn/kratos-kit/pprof"
	"github.com/liujitcn/kratos-kit/queue"
	configs2 "github.com/liujitcn/shop-admin/server/internal/configs"
	data3 "github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/server"
	"github.com/liujitcn/shop-admin/server/internal/service/admin"
	biz2 "github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/task"
	"github.com/liujitcn/shop-admin/server/internal/service/pay"
	biz3 "github.com/liujitcn/shop-admin/server/internal/service/pay/biz"
	"github.com/liujitcn/shop-base/server/configs"
	"github.com/liujitcn/shop-base/server/core"
	data2 "github.com/liujitcn/shop-base/server/data"
	"github.com/liujitcn/shop-base/server/middleware"
	"github.com/liujitcn/shop-base/server/service/config"
	biz4 "github.com/liujitcn/shop-base/server/service/config/biz"
	"github.com/liujitcn/shop-base/server/service/file"
	biz5 "github.com/liujitcn/shop-base/server/service/file/biz"
	"github.com/liujitcn/shop-base/server/service/login"
	"github.com/liujitcn/shop-base/server/service/login/biz"
	"github.com/liujitcn/shop-gorm-gen/data"
)

import (
	_ "github.com/liujitcn/kratos-kit/database/gorm/driver/mysql"
	_ "github.com/liujitcn/kratos-kit/logger/zap"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	authentication_Jwt := configs.ParseAuthnJwt(context)
	authenticator := middleware.NewAuthenticator(authentication_Jwt)
	confData, err := configs.ParseData(context)
	if err != nil {
		return nil, nil, err
	}
	data_Database := configs.ParseDatabase(confData)
	client, cleanup, err := gorm.NewGormClient(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(client)
	baseUserRepo := data2.NewBaseUserRepo(dataData)
	baseUserCase := biz.NewBaseUserCase(baseUserRepo)
	engine, err := middleware.NewAuthzEngine()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	data_Redis := configs.ParseRedis(confData)
	cacheCache, cleanup2, err := cache.NewCache(data_Redis)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userToken := middleware.NewUserToken(authentication_Jwt, cacheCache, authenticator)
	grpcMiddlewares := server.NewGrpcMiddleware(context, authenticator, baseUserCase, engine, userToken, authentication_Jwt)
	data_Queue := configs.ParseQueue(confData)
	queueQueue, cleanup3, err := queue.NewQueue(data_Redis, data_Queue)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	confPprof, err := configs.ParsePprof(context)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pprofPprof, err := pprof.NewPprof(confPprof)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	shopCore, cleanup4, err := core.NewShopCore(context, cacheCache, queueQueue, client, pprofPprof, userToken)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataBaseUserRepo := data3.NewBaseUserRepo(dataData)
	baseDeptRepo := data3.NewBaseDeptRepo(dataData)
	bizBaseUserCase := biz2.NewBaseUserCase(dataBaseUserRepo, baseDeptRepo)
	transaction := data.NewTransaction(dataData)
	baseRoleRepo := data3.NewBaseRoleRepo(dataData)
	casbinRuleRepo := data3.NewCasbinRuleRepo(dataData)
	baseMenuRepo := data3.NewBaseMenuRepo(dataData)
	baseApiRepo := data3.NewBaseApiRepo(dataData)
	baseApiCase := biz2.NewBaseApiCase(baseApiRepo)
	casbinRuleCase, err := biz2.NewCasbinRuleCase(casbinRuleRepo, baseMenuRepo, baseRoleRepo, baseApiCase, engine)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseRoleCase := biz2.NewBaseRoleCase(transaction, baseRoleRepo, casbinRuleCase)
	baseDeptCase := biz2.NewBaseDeptCase(baseDeptRepo)
	baseMenuCase := biz2.NewBaseMenuCase(transaction, baseMenuRepo, casbinRuleCase)
	authService := admin.NewAuthService(shopCore, bizBaseUserCase, baseRoleCase, baseDeptCase, baseMenuCase)
	baseApiService, err := admin.NewBaseApiService(shopCore, baseApiCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseConfigRepo := data3.NewBaseConfigRepo(dataData)
	baseConfigCase := biz2.NewBaseConfigCase(baseConfigRepo)
	baseConfigService, err := admin.NewBaseConfigService(shopCore, baseConfigCase)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseDeptService := admin.NewBaseDeptService(shopCore, baseDeptCase)
	baseDictRepo := data3.NewBaseDictRepo(dataData)
	baseDictCase := biz2.NewBaseDictCase(baseDictRepo)
	baseDictItemRepo := data3.NewBaseDictItemRepo(dataData)
	baseDictItemCase := biz2.NewBaseDictItemCase(baseDictRepo, baseDictItemRepo)
	baseDictService := admin.NewBaseDictService(shopCore, baseDictCase, baseDictItemCase)
	baseJobRepo := data3.NewBaseJobRepo(dataData)
	confOSS, err := configs.ParseOss(context)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ossOSS := oss.NewOSS(confOSS)
	shopAdminServerConfig := configs2.NewShopAdminServerConfig(context)
	wxPay, err := configs2.ParseWxPay(shopAdminServerConfig)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	wxPayCase, err := biz3.NewWxPayCase(wxPay)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	payBillRepo := data3.NewPayBillRepo(dataData)
	payBillCase := biz3.NewPayBillCase(payBillRepo)
	orderPaymentRepo := data3.NewOrderPaymentRepo(dataData)
	orderRefundRepo := data3.NewOrderRefundRepo(dataData)
	tradeBill := task.NewTradeBill(ossOSS, transaction, wxPayCase, payBillCase, orderPaymentRepo, orderRefundRepo)
	v := task.NewTaskList(tradeBill)
	baseJobCase := biz2.NewBaseJobCase(baseJobRepo, v)
	baseJobLogRepo := data3.NewBaseJobLogRepo(dataData)
	baseJobLogCase := biz2.NewBaseJobLogCase(baseJobLogRepo)
	baseJobService := admin.NewBaseJobService(shopCore, baseJobCase, baseJobLogCase)
	baseLogRepo := data3.NewBaseLogRepo(dataData)
	baseLogCase := biz2.NewBaseLogCase(baseLogRepo)
	baseLogService := admin.NewBaseLogService(shopCore, baseLogCase)
	baseMenuService := admin.NewBaseMenuService(shopCore, baseMenuCase, casbinRuleCase)
	baseRoleService := admin.NewBaseRoleService(shopCore, baseRoleCase)
	baseUserService := admin.NewBaseUserService(shopCore, bizBaseUserCase)
	goodsRepo := data3.NewGoodsRepo(dataData)
	goodsCategoryRepo := data3.NewGoodsCategoryRepo(dataData)
	goodsPropRepo := data3.NewGoodsPropRepo(dataData)
	goodsPropCase := biz2.NewGoodsPropCase(goodsPropRepo)
	goodsSpecRepo := data3.NewGoodsSpecRepo(dataData)
	goodsSpecCase := biz2.NewGoodsSpecCase(goodsSpecRepo)
	goodsSkuRepo := data3.NewGoodsSkuRepo(dataData)
	goodsSkuCase := biz2.NewGoodsSkuCase(goodsSkuRepo)
	goodsCase := biz2.NewGoodsCase(transaction, goodsRepo, goodsCategoryRepo, goodsPropCase, goodsSpecCase, goodsSkuCase)
	goodsCategoryCase := biz2.NewGoodsCategoryCase(goodsCategoryRepo)
	orderAddressRepo := data3.NewOrderAddressRepo(dataData)
	orderAddressCase := biz2.NewOrderAddressCase(orderAddressRepo)
	orderRepo := data3.NewOrderRepo(dataData)
	orderCancelRepo := data3.NewOrderCancelRepo(dataData)
	orderCancelCase := biz2.NewOrderCancelCase(orderCancelRepo)
	orderGoodsRepo := data3.NewOrderGoodsRepo(dataData)
	orderGoodsCase := biz2.NewOrderGoodsCase(orderGoodsRepo)
	orderLogisticsRepo := data3.NewOrderLogisticsRepo(dataData)
	orderLogisticsCase := biz2.NewOrderLogisticsCase(orderLogisticsRepo)
	orderPaymentCase := biz2.NewOrderPaymentCase(orderPaymentRepo)
	orderRefundCase := biz2.NewOrderRefundCase(orderRefundRepo)
	orderCase := biz2.NewOrderCase(transaction, orderAddressCase, orderRepo, orderCancelCase, orderGoodsCase, orderLogisticsCase, orderPaymentCase, orderRefundCase, bizBaseUserCase, baseDictItemCase, wxPayCase)
	dashboardCase := biz2.NewDashboardCase(bizBaseUserCase, goodsCase, goodsCategoryCase, orderCase, orderGoodsCase, baseDictCase, baseDictItemCase)
	dashboardService := admin.NewDashboardService(shopCore, dashboardCase)
	goodsCategoryService := admin.NewGoodsCategoryService(shopCore, goodsCategoryCase)
	goodsService := admin.NewGoodsService(shopCore, goodsCase, goodsCategoryCase)
	goodsPropService := admin.NewGoodsPropService(shopCore, goodsPropCase)
	goodsSkuService := admin.NewGoodsSkuService(shopCore, goodsSkuCase)
	goodsSpecService := admin.NewGoodsSpecService(shopCore, goodsSpecCase)
	orderService := admin.NewOrderService(shopCore, orderCase)
	bizPayBillCase := biz2.NewPayBillCase(payBillRepo)
	payBillService := admin.NewPayBillService(shopCore, bizPayBillCase)
	shopBannerRepo := data3.NewShopBannerRepo(dataData)
	shopBannerCase := biz2.NewShopBannerCase(shopBannerRepo)
	shopBannerService := admin.NewShopBannerService(shopCore, shopBannerCase)
	shopHotRepo := data3.NewShopHotRepo(dataData)
	shopHotCase := biz2.NewShopHotCase(shopHotRepo)
	shopHotItemRepo := data3.NewShopHotItemRepo(dataData)
	shopHotGoodsRepo := data3.NewShopHotGoodsRepo(dataData)
	shopHotItemCase := biz2.NewShopHotItemCase(transaction, shopHotRepo, shopHotItemRepo, shopHotGoodsRepo)
	shopHotService := admin.NewShopHotService(shopCore, shopHotCase, shopHotItemCase)
	shopServiceRepo := data3.NewShopServiceRepo(dataData)
	shopServiceCase := biz2.NewShopServiceCase(shopServiceRepo)
	shopServiceService := admin.NewShopServiceService(shopCore, shopServiceCase)
	userStoreRepo := data3.NewUserStoreRepo(dataData)
	baseAreaRepo := data3.NewBaseAreaRepo(dataData)
	baseAreaCase := biz2.NewBaseAreaCase(baseAreaRepo)
	userStoreCase := biz2.NewUserStoreCase(transaction, userStoreRepo, baseAreaCase, bizBaseUserCase, baseRoleCase)
	userStoreService := admin.NewUserStoreService(shopCore, userStoreCase)
	dataBaseConfigRepo := data2.NewBaseConfigRepo(dataData)
	configCase := biz4.NewConfigCase(dataBaseConfigRepo)
	configService := config.NewConfigService(shopCore, configCase)
	fileCase := biz5.NewFileCase(ossOSS)
	fileService := file.NewFileService(shopCore, fileCase)
	dataBaseRoleRepo := data2.NewBaseRoleRepo(dataData)
	bizBaseRoleCase := biz.NewBaseRoleCase(transaction, dataBaseRoleRepo)
	dataBaseDeptRepo := data2.NewBaseDeptRepo(dataData)
	bizBaseDeptCase := biz.NewBaseDeptCase(dataBaseDeptRepo)
	loginService := login.NewLoginService(shopCore, baseUserCase, bizBaseRoleCase, bizBaseDeptCase)
	orderSchedulerCase := biz3.NewOrderSchedulerCase()
	payCase := biz3.NewPayCase(transaction, orderRepo, orderGoodsRepo, orderPaymentRepo, orderRefundRepo, orderSchedulerCase, wxPayCase)
	payService := pay.NewPayService(shopCore, payCase)
	grpcServer, err := server.NewGRPCServer(context, grpcMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, dashboardService, goodsCategoryService, goodsService, goodsPropService, goodsSkuService, goodsSpecService, orderService, payBillService, shopBannerService, shopHotService, shopServiceService, userStoreService, configService, fileService, loginService, payService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpMiddlewares := server.NewHttpMiddleware(context, authenticator, baseUserCase, engine, userToken, authentication_Jwt)
	httpServer, err := server.NewHttpServer(context, httpMiddlewares, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, dashboardService, goodsCategoryService, goodsService, goodsPropService, goodsSkuService, goodsSpecService, orderService, payBillService, shopBannerService, shopHotService, shopServiceService, userStoreService, configService, fileService, loginService, payService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
