// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/liujitcn/go-sdk/cache"
	"github.com/liujitcn/go-sdk/gorm"
	"github.com/liujitcn/go-sdk/oss"
	"github.com/liujitcn/shop-admin/server/internal/configs"
	data2 "github.com/liujitcn/shop-admin/server/internal/data"
	"github.com/liujitcn/shop-admin/server/internal/sdk"
	"github.com/liujitcn/shop-admin/server/internal/server"
	"github.com/liujitcn/shop-admin/server/internal/service/admin"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/admin/task"
	"github.com/liujitcn/shop-admin/server/internal/service/app"
	biz3 "github.com/liujitcn/shop-admin/server/internal/service/app/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/config"
	biz4 "github.com/liujitcn/shop-admin/server/internal/service/config/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/file"
	biz5 "github.com/liujitcn/shop-admin/server/internal/service/file/biz"
	"github.com/liujitcn/shop-admin/server/internal/service/login"
	"github.com/liujitcn/shop-admin/server/internal/service/pay"
	biz2 "github.com/liujitcn/shop-admin/server/internal/service/pay/biz"
	"github.com/liujitcn/shop-gorm-gen/data"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/logger/zap"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	authentication_Jwt := configs.ParseAuthnJwt(context)
	authenticator := sdk.NewAuthenticator(authentication_Jwt)
	v := sdk.RegisterMigrateModels()
	client, err := gorm.NewGormClient(context, v)
	if err != nil {
		return nil, nil, err
	}
	dataData := data.NewData(client)
	baseUserRepo := data2.NewBaseUserRepo(dataData)
	baseDeptRepo := data2.NewBaseDeptRepo(dataData)
	baseUserCase := biz.NewBaseUserCase(baseUserRepo, baseDeptRepo)
	engine, err := sdk.NewAuthzEngine()
	if err != nil {
		return nil, nil, err
	}
	cacheCache, cleanup, err := cache.NewCache(context)
	if err != nil {
		return nil, nil, err
	}
	userToken := sdk.NewUserToken(cacheCache, authenticator)
	shopAdminServerConfig := configs.NewShopAdminServerConfig(context)
	jwt := configs.ParseJwt(shopAdminServerConfig)
	v2 := server.NewHttpMiddleware(context, authenticator, baseUserCase, engine, userToken, jwt)
	transaction := data.NewTransaction(dataData)
	baseRoleRepo := data2.NewBaseRoleRepo(dataData)
	casbinRuleRepo := data2.NewCasbinRuleRepo(dataData)
	baseMenuRepo := data2.NewBaseMenuRepo(dataData)
	baseApiRepo := data2.NewBaseApiRepo(dataData)
	baseApiCase := biz.NewBaseApiCase(baseApiRepo)
	casbinRuleCase, err := biz.NewCasbinRuleCase(casbinRuleRepo, baseMenuRepo, baseRoleRepo, baseApiCase, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseRoleCase := biz.NewBaseRoleCase(transaction, baseRoleRepo, casbinRuleCase)
	baseDeptCase := biz.NewBaseDeptCase(baseDeptRepo)
	baseMenuCase := biz.NewBaseMenuCase(transaction, baseMenuRepo, casbinRuleCase)
	authService := admin.NewAuthService(context, baseUserCase, baseRoleCase, baseDeptCase, baseMenuCase, userToken)
	baseApiService, err := admin.NewBaseApiService(context, baseApiCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseConfigRepo := data2.NewBaseConfigRepo(dataData)
	baseConfigCase := biz.NewBaseConfigCase(baseConfigRepo)
	baseConfigService, err := admin.NewBaseConfigService(context, baseConfigCase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseDeptService := admin.NewBaseDeptService(context, baseDeptCase)
	baseDictRepo := data2.NewBaseDictRepo(dataData)
	baseDictCase := biz.NewBaseDictCase(baseDictRepo)
	baseDictItemRepo := data2.NewBaseDictItemRepo(dataData)
	baseDictItemCase := biz.NewBaseDictItemCase(baseDictRepo, baseDictItemRepo)
	baseDictService := admin.NewBaseDictService(context, baseDictCase, baseDictItemCase)
	baseJobRepo := data2.NewBaseJobRepo(dataData)
	ossOSS := oss.NewOSS(context)
	wxPay, err := configs.ParseWxPay(shopAdminServerConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	wxPayCase, err := biz2.NewWxPayCase(wxPay)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	payBillRepo := data2.NewPayBillRepo(dataData)
	payBillCase := biz2.NewPayBillCase(payBillRepo)
	orderPaymentRepo := data2.NewOrderPaymentRepo(dataData)
	orderRefundRepo := data2.NewOrderRefundRepo(dataData)
	tradeBill := task.NewTradeBill(ossOSS, transaction, wxPayCase, payBillCase, orderPaymentRepo, orderRefundRepo)
	v3 := task.NewTaskList(tradeBill)
	baseJobCase := biz.NewBaseJobCase(baseJobRepo, v3)
	baseJobLogRepo := data2.NewBaseJobLogRepo(dataData)
	baseJobLogCase := biz.NewBaseJobLogCase(baseJobLogRepo)
	baseJobService := admin.NewBaseJobService(context, baseJobCase, baseJobLogCase)
	baseLogRepo := data2.NewBaseLogRepo(dataData)
	baseLogCase := biz.NewBaseLogCase(baseLogRepo)
	baseLogService := admin.NewBaseLogService(context, baseLogCase)
	baseMenuService := admin.NewBaseMenuService(context, baseMenuCase, casbinRuleCase)
	baseRoleService := admin.NewBaseRoleService(context, baseRoleCase)
	baseUserService := admin.NewBaseUserService(context, baseUserCase)
	goodsRepo := data2.NewGoodsRepo(dataData)
	goodsCategoryRepo := data2.NewGoodsCategoryRepo(dataData)
	goodsPropRepo := data2.NewGoodsPropRepo(dataData)
	goodsPropCase := biz.NewGoodsPropCase(goodsPropRepo)
	goodsSpecRepo := data2.NewGoodsSpecRepo(dataData)
	goodsSpecCase := biz.NewGoodsSpecCase(goodsSpecRepo)
	goodsSkuRepo := data2.NewGoodsSkuRepo(dataData)
	goodsSkuCase := biz.NewGoodsSkuCase(goodsSkuRepo)
	goodsCase := biz.NewGoodsCase(transaction, goodsRepo, goodsCategoryRepo, goodsPropCase, goodsSpecCase, goodsSkuCase)
	goodsCategoryCase := biz.NewGoodsCategoryCase(goodsCategoryRepo)
	orderAddressRepo := data2.NewOrderAddressRepo(dataData)
	orderAddressCase := biz.NewOrderAddressCase(orderAddressRepo)
	orderRepo := data2.NewOrderRepo(dataData)
	orderCancelRepo := data2.NewOrderCancelRepo(dataData)
	orderCancelCase := biz.NewOrderCancelCase(orderCancelRepo)
	orderGoodsRepo := data2.NewOrderGoodsRepo(dataData)
	orderGoodsCase := biz.NewOrderGoodsCase(orderGoodsRepo)
	orderLogisticsRepo := data2.NewOrderLogisticsRepo(dataData)
	orderLogisticsCase := biz.NewOrderLogisticsCase(orderLogisticsRepo)
	orderPaymentCase := biz.NewOrderPaymentCase(orderPaymentRepo)
	orderRefundCase := biz.NewOrderRefundCase(orderRefundRepo)
	orderCase := biz.NewOrderCase(transaction, orderAddressCase, orderRepo, orderCancelCase, orderGoodsCase, orderLogisticsCase, orderPaymentCase, orderRefundCase, baseUserCase, baseDictItemCase, wxPayCase)
	dashboardCase := biz.NewDashboardCase(baseUserCase, goodsCase, goodsCategoryCase, orderCase, orderGoodsCase, baseDictCase, baseDictItemCase)
	dashboardService := admin.NewDashboardService(context, dashboardCase)
	goodsCategoryService := admin.NewGoodsCategoryService(context, goodsCategoryCase)
	goodsService := admin.NewGoodsService(context, goodsCase, goodsCategoryCase)
	goodsPropService := admin.NewGoodsPropService(context, goodsPropCase)
	goodsSkuService := admin.NewGoodsSkuService(context, goodsSkuCase)
	goodsSpecService := admin.NewGoodsSpecService(context, goodsSpecCase)
	orderService := admin.NewOrderService(context, orderCase)
	bizPayBillCase := biz.NewPayBillCase(payBillRepo)
	payBillService := admin.NewPayBillService(context, bizPayBillCase)
	shopBannerRepo := data2.NewShopBannerRepo(dataData)
	shopBannerCase := biz.NewShopBannerCase(shopBannerRepo)
	shopBannerService := admin.NewShopBannerService(context, shopBannerCase)
	shopHotRepo := data2.NewShopHotRepo(dataData)
	shopHotCase := biz.NewShopHotCase(shopHotRepo)
	shopHotItemRepo := data2.NewShopHotItemRepo(dataData)
	shopHotGoodsRepo := data2.NewShopHotGoodsRepo(dataData)
	shopHotItemCase := biz.NewShopHotItemCase(transaction, shopHotRepo, shopHotItemRepo, shopHotGoodsRepo)
	shopHotService := admin.NewShopHotService(context, shopHotCase, shopHotItemCase)
	shopServiceRepo := data2.NewShopServiceRepo(dataData)
	shopServiceCase := biz.NewShopServiceCase(shopServiceRepo)
	shopServiceService := admin.NewShopServiceService(context, shopServiceCase)
	userStoreRepo := data2.NewUserStoreRepo(dataData)
	baseAreaRepo := data2.NewBaseAreaRepo(dataData)
	baseAreaCase := biz.NewBaseAreaCase(baseAreaRepo)
	userStoreCase := biz.NewUserStoreCase(transaction, userStoreRepo, baseAreaCase, baseUserCase, baseRoleCase)
	userStoreService := admin.NewUserStoreService(context, userStoreCase)
	bizShopServiceCase := biz3.NewShopServiceCase(shopServiceRepo)
	appShopServiceService := app.NewShopServiceService(context, bizShopServiceCase)
	configCase := biz4.NewConfigCase(baseConfigRepo)
	configService := config.NewConfigService(context, configCase)
	fileCase := biz5.NewFileCase(ossOSS)
	fileService := file.NewFileService(context, fileCase)
	loginService := login.NewLoginService(context, cacheCache, userToken)
	orderSchedulerCase := biz2.NewOrderSchedulerCase()
	payCase := biz2.NewPayCase(transaction, orderRepo, orderGoodsRepo, orderPaymentRepo, orderRefundRepo, orderSchedulerCase, wxPayCase)
	payService := pay.NewPayService(context, payCase)
	httpServer, err := server.NewHttpServer(context, v2, authService, baseApiService, baseConfigService, baseDeptService, baseDictService, baseJobService, baseLogService, baseMenuService, baseRoleService, baseUserService, dashboardService, goodsCategoryService, goodsService, goodsPropService, goodsSkuService, goodsSpecService, orderService, payBillService, shopBannerService, shopHotService, shopServiceService, userStoreService, appShopServiceService, configService, fileService, loginService, payService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	kratosApp := newApp(context, httpServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
